import type { PromptKind, SeedPrompt } from './seed-prompts';
import type { WritingType } from './units';

function task(
  kind: PromptKind,
  module_id: number,
  prompt_type: WritingType,
  title: string,
  description: string,
  hint_points: [string, string, string],
  sample_answer_high: string,
  sample_answer_medium: string,
): SeedPrompt {
  return {
    title,
    description,
    prompt_type,
    module_id,
    hint_points,
    sample_answer_high,
    sample_answer_medium,
    is_locked: false,
    time_limit_minutes: 30,
    is_active: true,
    kind,
  };
}

const practice = (
  module_id: number,
  prompt_type: WritingType,
  title: string,
  description: string,
  hint_points: [string, string, string],
  sample_answer_high: string,
  sample_answer_medium: string,
) =>
  task(
    'practice',
    module_id,
    prompt_type,
    title,
    description,
    hint_points,
    sample_answer_high,
    sample_answer_medium,
  );

const review = (
  module_id: number,
  prompt_type: WritingType,
  title: string,
  description: string,
  hint_points: [string, string, string],
  sample_answer_high: string,
  sample_answer_medium: string,
) =>
  task(
    'test',
    module_id,
    prompt_type,
    title,
    description,
    hint_points,
    sample_answer_high,
    sample_answer_medium,
  );

/** Extra practice tasks so every unit has three full writing tasks. */
export const EXTRA_PRACTICE_PROMPTS: SeedPrompt[] = [
  practice(
    1,
    'narrative',
    'The empty seat',
    'Every afternoon the same seat on the bus is empty. Today, a note is taped to the window above it.\n\nWrite a narrative about what happens when you read the note and take the seat.',
    [
      'Hook the reader and set the scene on the bus',
      'Build a problem or change in the middle',
      'Finish with a clear ending tied to the note',
    ],
    'The vinyl seat still held a dent, as if someone had only just stood up. A folded scrap said: Don’t let them take the last stop.\n\nI sat. The bus hissed forward. At the river bend a boy in a too-big blazer mouthed “you came”, and the lights of the depot flickered like a warning.\n\nWe got off one stop early. Behind us the last bus sighed into the dark, empty again — except the note, now in my pocket, still warm.',
    'I saw an empty seat with a note. I sat down and something strange happened. I got off the bus and the story ended.',
  ),
  practice(
    1,
    'narrative',
    'After the storm',
    'A huge storm has passed overnight. In the morning, something in your street has changed.\n\nWrite a narrative about the first person who steps outside and what they discover.',
    [
      'Show the street after the storm with precise detail',
      'Introduce a discovery that changes the character’s plan',
      'Resolve the discovery without starting a new story',
    ],
    'Gutters ticked. A letterbox lay on its side, mouth open, spilling soggy envelopes like white fish.\n\nMaya lifted one. It was addressed to her — dated tomorrow. Her hands shook as the ink named a place she had never been allowed to go: the old boatshed.\n\nShe went. The door was already ajar. Inside, a dry towel waited, as if the storm had expected her, and had left the rest of the day in her hands.',
    'After the storm I went outside. Things were messy. I found something surprising and then I went home.',
  ),
  practice(
    2,
    'diary_entry',
    'The day the power went out',
    'Write a diary entry about a day when the power went out at home from late afternoon until night. Include what you did, who you were with, and how you felt when the lights came back.',
    [
      'Keep a first-person diary voice with a date or Dear Diary',
      'Describe what happened in time order',
      'End with a feeling or thought about the dark hours',
    ],
    'Dear Diary,\nThe fridge hummed once, then the house went quiet as a held breath.\n\nMum lit the camping lantern. We ate bread and cold mango at the table and told the story of the possum on the roof until we were actually laughing. I finished homework by the window while the sky turned the colour of tea.\n\nWhen the lights slammed back, the TV shouted and nobody moved to turn it on. I liked us better in the dark.',
    'Dear Diary,\nThe power went out. It was boring at first. We used a torch and talked. I was happy when the lights came back.',
  ),
  practice(
    3,
    'news_report',
    'Visitor at the school gate',
    'An unexpected visitor caused a stir at a local primary school this morning.\n\nWrite a news report for the local paper. Include what happened, who was affected, and at least one short quote.',
    [
      'Put the main facts (who, what, where, when) near the start',
      'Stay in a calm third-person news voice',
      'Include a short, correctly punctuated quote',
    ],
    'EMU HALTS MORNING DROP-OFF\n\nAn emu wandered onto Riverview Public’s front path at 8:40am on Tuesday, delaying drop-off for twenty minutes.\n\nPrincipal Dana Holt said staff kept students inside: “The bird was calm, but we were not taking chances.” Wildlife officer Sam Reed guided it towards the reserve after it pecked at a lunchbox.\n\nNo one was hurt. Lessons resumed after recess, and the school has asked families to keep gates closed.',
    'There was an emu at school. People were surprised. A teacher said it was unusual. Then it left and school went back to normal.',
  ),
  practice(
    4,
    'explanation',
    'How recycling works at home',
    'Write a clear explanation for a younger student about how household recycling works, from the bin at home to what happens next.\n\nExplain the steps in order and why they matter.',
    [
      'Say what you are explaining in the first lines',
      'Order the steps so a younger reader can follow',
      'Use simple cause-and-effect words (this means, so, because)',
    ],
    'HOW YOUR RECYCLING BIN HELPS\n\nRecycling means giving used materials another job instead of burying them.\n\nFirst, you rinse a bottle or box so leftover food does not spoil the rest. Then you put paper, plastic bottles and cans in the yellow bin — not soft plastic bags, which tangle machines.\n\nA truck takes the bin to a sorting centre. Machines and workers separate the types. Clean materials can be melted or pulped and made into new things.\n\nIf the wrong rubbish goes in, a whole load can be wasted. That is why the first small step at home matters.',
    'Recycling is when you put rubbish in a special bin. A truck takes it away. Then it is made into new things. You should rinse bottles first.',
  ),
  practice(
    4,
    'explanation',
    'Why we have seasons',
    'Write an explanation of why Australia has seasons.\n\nHelp a reader who has not studied this yet. Keep the order clear: tilt, sunlight, and what we notice.',
    [
      'Name the topic clearly at the start',
      'Explain tilt and sunlight in a sensible order',
      'Link each step to what people notice in summer or winter',
    ],
    'WHY THE SEASONS CHANGE\n\nEarth is tilted as it travels around the Sun. That tilt is the main reason we have seasons.\n\nWhen our part of the planet leans towards the Sun, sunlight hits more directly and days last longer. The ground and air warm up — summer. When we lean away, the same sunlight is spread out and days are shorter, so winter arrives.\n\nAustralia’s summer happens when the southern half leans towards the Sun. This is why Christmas can be hot here, even though it is winter in the north.',
    'We have seasons because the Earth is tilted. Sometimes we get more sun and it is summer. Sometimes we get less and it is winter.',
  ),
  practice(
    5,
    'advice_sheet',
    'Cross country week',
    'Write an advice sheet for students who are nervous about school cross country.\n\nGive a short welcome, two or three useful tips, and a kind close.',
    [
      'Use a friendly “you” and a scannable layout',
      'Give practical tips a student can actually use',
      'Keep the tone encouraging, not bossy',
    ],
    'CROSS COUNTRY WITHOUT THE PANIC\n\nYou do not have to love running. You only have to look after yourself on the day.\n\n1. Practise a loop twice this week, even walking the hills.\n2. Eat a simple breakfast and bring a water bottle.\n3. Start steady. Overtaking in the first 200 metres usually backfires.\n\nCheer the person beside you. Finishing with a red face still counts. See you at the start line — you’ve got this.',
    'Advice for Cross Country\n\nTrain a bit. Drink water. Don’t start too fast. You will be fine. Good luck.',
  ),
  practice(
    6,
    'review',
    'A film worth the popcorn',
    'Write a review of a film or series you have watched for other students your age.\n\nGive your overall view early, reasons, and who should watch it. Avoid big spoilers.',
    [
      'Name the title and your overall view near the start',
      'Give fair reasons without spoiling the ending',
      'Finish with a clear recommendation',
    ],
    'A QUIET FILM THAT STILL RACES\n\n*The Peanut Butter Falcon* is a small adventure with a huge heart. A boy who wants more than the life planned for him teams up with a drifter, and the river does the rest.\n\nI liked it because the humour is kind, not mean, and the friendship feels earned. The pace is a little slow in the middle, but the last stretch is warm without turning sugary.\n\nI would recommend this to anyone who likes road (or river) stories and characters who try, even when the world is awkward.',
    'I watched a film and it was good. The characters were nice. Some parts were slow. I recommend it to people who like adventure.',
  ),
  practice(
    6,
    'review',
    'A place I would go back to',
    'Write a review of a place you have visited (a park, museum, pool, or town) for other families.\n\nHelp them decide whether to go.',
    [
      'Say what the place is and your overall view',
      'Give specific reasons (not just “it was fun”)',
      'Recommend who would enjoy it',
    ],
    'POWERHOUSE MUSEUM: WORTH THE QUEUE\n\nThe Powerhouse in Sydney is a noisy, brilliant attic of inventions. We spent three hours and still missed a floor.\n\nThe steam engines and space displays make science feel like a story, not a worksheet. It gets packed at lunch, and the cafe is average, but the hands-on rooms kept even the wriggly cousin busy.\n\nGo if you have a curious 8-to-12-year-old and comfortable shoes. Skip it if you want peace and quiet — this place hums.',
    'I went to a museum. It was interesting and a bit crowded. I think families would like it. The food was okay.',
  ),
  practice(
    7,
    'advertisement',
    'Advertise the school fair',
    'Write a short advertisement to persuade families to come to this year’s school fair.\n\nInclude a catchy heading, what is on offer, and a clear “what to do next”.',
    [
      'Open with a short, lively heading',
      'Tell the reader what they will find',
      'End with a call to action (time, place, or how to join in)',
    ],
    'SATURDAY GLOWS AT RIVERVIEW FAIR\n\nOne afternoon. A hundred small wonders.\n\nFace-painting that actually looks like a tiger, a silent-disco hoop, second-hand books for a gold coin, and a sausage sizzle that runs out if you dawdle.\n\nBring coins, a bag, and someone you like.\nSaturday 2–6pm, school oval. Enter through the hall gates.\nCome for the cake stall. Stay because the oval smells like spring.',
    'Come to the school fair! There will be food and games. It will be fun. See you there on Saturday.',
  ),
  practice(
    7,
    'advertisement',
    'Join the after-school makers club',
    'Write an advertisement for a new after-school makers club (building, coding, or craft).\n\nAim it at students, not teachers.',
    [
      'Match the reader (students) with a clear benefit',
      'Use lively but controlled language — no shouting insults',
      'Tell them how to join',
    ],
    'MAKE SOMETHING THAT DIDN’T EXIST THIS MORNING\n\nMakers Club is Tuesdays, 3:15–4:15, in the art room. Bring curiosity; we supply cardboard, code, and glue-gun courage.\n\nLast term we built a marble run that ate a teacher’s hat (on purpose).\n\nSign the sheet outside the library by Friday. First six weeks are free.\nYour backpack is about to get more interesting.',
    'Join Makers Club after school. You can build things. It is fun. Sign up at the library.',
  ),
  practice(
    8,
    'persuasive_text',
    'Phones at school',
    'Write a persuasive text arguing whether students your age should be allowed to use phones at school.\n\nTake a clear position, give reasons, and answer the other side.',
    [
      'State your position in the opening',
      'Give one reason per paragraph with a short example',
      'Fairly mention the other view, then finish firmly',
    ],
    'PHONES BELONG IN BAGS UNTIL THE BELL\n\nStudents should not use phones during school hours, except in a real emergency.\n\nLessons need attention. A buzzing pocket steals the next instruction, and then the student is lost for ten minutes. At lunch, faces in screens mean fewer games and fewer new friends.\n\nSome families say phones keep children safe. That is fair — phones can stay at the office or switched off in bags, and be used if a parent must be called.\n\nA school day is short. Keep the phones quiet so the learning — and the playground — can be loud in the right way.',
    'I think phones should not be used at school. They distract people. Some people say they are for safety, but you can keep them in your bag. So no phones in class.',
  ),
  practice(
    8,
    'persuasive_text',
    'A plastic-free canteen',
    'Write a persuasive text arguing whether the school canteen should stop using single-use plastic.\n\nBe polite to readers who disagree.',
    [
      'Take a side and keep it',
      'Use a simple linking word for a reason (because, however)',
      'Close by restating the position',
    ],
    'LESS PLASTIC ON THE LUNCH TRAY\n\nOur canteen should stop single-use plastic this year.\n\nWrappers and forks from one lunch sit in the bin for hundreds of years. We already have a compost bucket; paper trays and a water-bottle refill tap would cut the rest.\n\nHowever, some people worry that food will cost more or get soggy. A short trial of paper boats for hot food would show what works before we change everything.\n\nA plastic-free canteen is not a lecture. It is a cleaner oval and a habit we can keep.',
    'The canteen should use less plastic. Plastic is bad for the environment. It might cost a bit more but it is worth it. We should try it.',
  ),
  practice(
    9,
    'formal_letter',
    'More hours for the library',
    'Write a formal letter to your principal asking for the school library to stay open one extra afternoon a week.\n\nUse a polite greeting, a clear purpose, and a proper sign-off.',
    [
      'Open with Dear … and why you are writing',
      'Give a calm, specific reason',
      'Close politely (Yours sincerely if you used the name)',
    ],
    'Dear Ms Holt,\n\nI am writing to ask if the library could stay open until 4:15pm on Thursdays.\n\nMany students wait for siblings and have nowhere quiet to finish homework. Last Thursday eight of us sat on the hall floor beside bags and sports gear. An extra hour would give us tables, books, and a teacher nearby.\n\nI would be grateful if you could consider a four-week trial. Thank you for your time.\n\nYours sincerely,\nAva Chen\nYear 6',
    'Dear Principal,\n\nPlease keep the library open longer. Students need a quiet place. Thank you.\n\nYours sincerely,\nAva',
  ),
  practice(
    9,
    'formal_letter',
    'A junior team request',
    'Write a formal letter to a local sports club asking them to start a junior team for your age group.\n\nBe polite, specific, and clear about what you want.',
    [
      'Use letter layout: greeting, purpose, sign-off',
      'Avoid slang',
      'Ask for one main thing, then a short thank-you',
    ],
    'Dear Coach Nguyen,\n\nI am writing to ask if Riverview Football Club could start a mixed junior team for Years 5–6 next season.\n\nAt present, players our age travel to two other suburbs. A local team would mean more children walking to training and fewer cars on Saturday. Twelve students at my school have already said they would join.\n\nI would be grateful if you could reply with the next step. Thank you for considering this.\n\nYours sincerely,\nJordan Lee',
    'Dear Coach,\n\nPlease make a junior team. We want to play closer to home. Thank you.\n\nYours sincerely,\nJordan',
  ),
  practice(
    10,
    'speech',
    'Looking after our oval',
    'Write a speech to your year group about looking after the school oval.\n\nGreet the listeners, make two or three points, and thank them at the end.',
    [
      'Open with a greeting or hook listeners can hear',
      'Use we/you so it sounds spoken',
      'Sum up and thank the audience',
    ],
    'Good morning, Year 5 and 6.\n\nHave we done enough for our oval? Yesterday I counted seventeen wrappers in the long grass after lunch.\n\nIf we each pick up five pieces of litter, the oval changes this week. If we stay on the paths when it is wet, the middle stays green for sport.\n\nWe like this place. Let’s treat it like it belongs to us — because it does.\nThank you.',
    'Hello everyone.\n\nPlease don’t drop rubbish on the oval. It looks bad and it is unsafe. Let’s look after it. Thank you.',
  ),
  practice(
    10,
    'speech',
    'Welcome to the new students',
    'Write a short welcome speech for new students joining your school this term.\n\nMake them feel they belong, and give one or two clear pieces of help.',
    [
      'Greet the room, including the new students',
      'Keep the language speakable and kind',
      'End with a thank-you or invitation',
    ],
    'Good morning, and especially good morning to the students who are new this term.\n\nWe know the map is confusing and the bell is loud. Sit with someone at lunch — if you cannot find a face, come to the library steps; Year 6 will be there on Friday.\n\nYou already belong here. We are glad you walked through the gate.\nThank you.',
    'Hello new students.\n\nWelcome to our school. Ask if you need help. We are happy you are here. Thank you.',
  ),
  practice(
    11,
    'email',
    'Group project meeting',
    'Write an email to your teacher asking for a short meeting about a group project that has gone off track.\n\nInclude a subject line, a polite greeting, the purpose, and a simple sign-off.',
    [
      'Use a clear subject line',
      'State the purpose in the first sentence after the greeting',
      'Keep it short and polite',
    ],
    'Subject: Request for a five-minute meeting — group project\n\nDear Mr Chen,\n\nCould we please meet for five minutes after school on Thursday about our history project? Two group members are unsure of the next step, and I would rather fix it now than hand in a messy draft.\n\nThank you for your time.\n\nKind regards,\nAva Chen',
    'Subject: meeting\n\nHi,\nWe need help with our project. Can we meet?\nThanks.',
  ),
];

/** One term-review test per unit. Creative 2, Informative 4, Persuasive 5. */
export const TERM_REVIEW_PROMPTS: SeedPrompt[] = [
  review(
    1,
    'narrative',
    'Term review: The last bus home',
    'The last bus is about to leave. You are not on it yet, and something is stopping you.\n\nWrite a narrative.\n\nYou have one attempt. Plan quickly, then write.',
    [
      'Open in the moment, not with “this is a story”',
      'Develop a problem and show how the character acts',
      'End by resolving that problem',
    ],
    'The doors sighed. My pass beeped red.\n\nI ran the wet footpath with a dripping science poster and a promise to Mum. A cyclist shouted; I skidded, caught the rail, and the driver — Mr Patel — lifted one eyebrow, then the lever.\n\nI fell into a seat that still held rain. The poster was ruined. The bus, somehow, was not. Home still existed, one stop at a time.',
    'I missed the bus almost. Then I caught it. I went home. It was a close thing.',
  ),
  review(
    2,
    'diary_entry',
    'Term review: The morning everything changed',
    'Write a diary entry about a morning when one small change made the whole day feel different.\n\nFirst person. One attempt only.',
    [
      'Use diary form (date or Dear Diary, I/me, a feeling)',
      'Keep events in time order',
      'Close with a thought about what the change meant',
    ],
    'Dear Diary,\nThe toast burned and I laughed, which I never do before 8am.\n\nDad had swapped our jobs: he packed lunches, I walked the dog. The dog chose every puddle. I arrived with wet socks and a story, and people actually asked to hear it.\n\nMaybe the day was waiting for me to notice it. I will burn the toast again tomorrow, on purpose.',
    'Dear Diary,\nSomething small changed this morning. I felt different all day. I hope tomorrow is good too.',
  ),
  review(
    3,
    'news_report',
    'Term review: Unexpected weather in town',
    'Write a news report about unexpected weather that affected your town for one afternoon.\n\nFacts first. One attempt only.',
    [
      'Headline and key facts near the top',
      'Calm report voice, not a personal recount',
      'Include at least one short quote',
    ],
    'HAIL STOPS SATURDAY SPORT\n\nMarble-sized hail swept across Riverview at 2:10pm on Saturday, forcing umpires to abandon junior soccer.\n\nCouncil ranger Priya Nair said drains coped: “We were lucky it lasted twelve minutes.” Shopkeepers on High Street reported dented awnings but no injuries.\n\nPlay will restart next week if fields dry.',
    'There was strange weather. Sport stopped. Someone said it was short. Then it was over.',
  ),
  review(
    4,
    'explanation',
    'Term review: Why bees matter',
    'Write an explanation for a younger student about why bees matter to people and plants.\n\nHow/why, in order. One attempt only.',
    [
      'Name the topic in the first sentence',
      'Explain the steps without turning it into a story',
      'Use simple linking words',
    ],
    'WHY BEES MATTER\n\nBees help plants make fruit and seeds by moving pollen from one flower to another.\n\nWhen a bee drinks nectar, pollen sticks to its body. The next flower receives that pollen, so the plant can grow apples, berries, or almonds. Without enough bees, many crops grow poorly.\n\nThis is why gardens and farms look after bees — they are small workers with a large job.',
    'Bees are important. They go to flowers. Then fruit can grow. That is why we need bees.',
  ),
  review(
    5,
    'advice_sheet',
    'Term review: Ready for a new school year',
    'Write an advice sheet for students starting a new school year at a bigger campus.\n\nFriendly, useful, easy to scan. One attempt only.',
    [
      'Welcome the reader, then give scannable tips',
      'Use “you” in a kind voice',
      'Close without turning it into a story',
    ],
    'NEW YEAR, BIGGER MAP\n\nYou will feel lost on day one. That is normal.\n\n1. Learn two landmarks: your locker block and the office.\n2. Pack a spare snack; lines are long.\n3. Ask one question a day — teachers expect it.\n\nBy week three the corridors shrink. Start kind, and the place starts kind back.',
    'Advice\n\nFind your classrooms. Be friendly. Ask for help. You will be okay.',
  ),
  review(
    6,
    'review',
    'Term review: A game or app',
    'Write a review of a game or app you know well, for other students.\n\nOpinion plus reasons. No big spoilers. One attempt only.',
    [
      'Name what you are reviewing and your view early',
      'Give reasons, not only “good” or “bad”',
      'Recommend who it would suit',
    ],
    'WORD GAMES FOR RAINY RECESS\n\n*Wordle* is a tiny daily puzzle that still makes a whole class groan together.\n\nI like it because it is fair: six guesses, same word, no pay-to-win. It can feel samey if you want a long adventure, and it is easy to overthink at breakfast.\n\nI would recommend it to people who like quiet challenges and a two-minute brain-warm-up — not to anyone hunting a huge story world.',
    'I reviewed a game. It is fun and a bit hard. I recommend it to people who like puzzles.',
  ),
  review(
    7,
    'advertisement',
    'Term review: The bottle that stays',
    'Write an advertisement for a reusable water bottle designed for school students.\n\nHook, offer, call to action. One attempt only.',
    [
      'A short heading and what the product does',
      'Persuade without insults or all-caps shouting',
      'Tell the reader what to do next',
    ],
    'STOP LOSING YOUR WATER — AND YOUR AFTERNOON\n\nThe Anchor Bottle fits the side pocket, does not taste of yesterday’s cordial, and has a lid you can open with one hand in the canteen line.\n\nName it on the band. Fill it at the tap. Keep your afternoon.\nAsk at the office this week — limited school colours.',
    'Buy this water bottle. It is good for school. Get one today.',
  ),
  review(
    8,
    'persuasive_text',
    'Term review: A longer lunch break',
    'Write a persuasive text arguing whether your school should have a longer lunch break.\n\nClear position, reasons, other side, firm ending. One attempt only.',
    [
      'State your position in the first lines',
      'Support it with reasons a school could actually use',
      'Restate the position at the end',
    ],
    'TEN MORE MINUTES OF LUNCH\n\nLunch should be ten minutes longer, even if the last lesson starts later.\n\nStudents eat too fast, then sit with stomach aches in maths. A little extra time means sport can finish without someone crying over a lost shoe.\n\nHowever, teachers need the afternoon for learning. Ten minutes is not a half-day. Trim one assembly speech and the time appears.\n\nA longer lunch is not laziness. It is room to be human before we think again.',
    'I think lunch should be longer. People need time to eat and play. Some people say lessons would be shorter, but only a little. So we should make lunch longer.',
  ),
  review(
    9,
    'formal_letter',
    'Term review: Repair the playground',
    'Write a formal letter to the local council about unsafe playground equipment in a nearby park.\n\nPolite, specific, one request. One attempt only.',
    [
      'Dear …, purpose first, polite sign-off',
      'Give a calm fact, not slang',
      'Thank the reader before you sign',
    ],
    'Dear Councillors,\n\nI am writing to ask if the broken climbing net in Green Street park can be repaired.\n\nThe path is uneven, and two students from my school have tripped near the frame this month. Families now avoid that corner, so the rest of the park feels crowded.\n\nI would be grateful if you could inspect it this term. Thank you for your time.\n\nYours faithfully,\nJordan Lee',
    'Dear Council,\n\nPlease fix the playground. It is not safe. Thank you.\n\nYours faithfully,\nJordan Lee',
  ),
  review(
    10,
    'speech',
    'Term review: Kindness this term',
    'Write a speech for assembly about why kindness still matters this term.\n\nSpoken to listeners. One attempt only.',
    [
      'Greet the listeners',
      'Make two or three hearable points',
      'Thank them and stop — do not start a new topic',
    ],
    'Good morning, everyone.\n\nKindness is not a poster. It is the spare pencil, the space on the bench, the “are you okay?” nobody scheduled.\n\nThis term will get busy. Tests will arrive. If we only look at scores, we will miss the student who is new, or tired, or both.\n\nNotice one person this week. Invite them in.\nThank you.',
    'Hello.\n\nPlease be kind this term. It helps everyone. Thank you.',
  ),
  review(
    11,
    'email',
    'Term review: Invite to the concert',
    'Write an email inviting a local community member (for example the mayor or a librarian) to the school concert.\n\nSubject, greeting, purpose, sign-off. One attempt only.',
    [
      'Clear subject line and polite greeting',
      'Purpose in the first sentence',
      'One main request, then a simple sign-off',
    ],
    'Subject: Invitation to Riverview Public concert, 18 September\n\nDear Mayor Chen,\n\nI am writing to invite you to our school concert on Thursday 18 September at 6pm in the hall.\n\nYear 5–6 will perform and would be honoured if you could say a short hello. Please let the office know if you can attend.\n\nKind regards,\nAva Chen\nYear 6 Music committee',
    'Subject: concert\n\nDear Mayor,\nPlease come to our concert. It is soon. Thank you.\nFrom Ava',
  ),
];

export const EXTRA_WRITING_PROMPTS: SeedPrompt[] = [
  ...EXTRA_PRACTICE_PROMPTS,
  ...TERM_REVIEW_PROMPTS,
];
