import type { WritingType } from '@/lib/units';

export const MINI_SKILLS = [
  'format',
  'audience',
  'vocabulary',
  'punctuation',
  'structure',
] as const;

export type MiniSkill = (typeof MINI_SKILLS)[number];

export const MINI_SKILL_LABELS: Record<MiniSkill, string> = {
  format: 'Format',
  audience: 'Audience',
  vocabulary: 'Word choice',
  punctuation: 'Punctuation',
  structure: 'Structure',
};

export type SeedMiniDrill = {
  slug: string;
  module_id: number;
  prompt_type: WritingType;
  skill: MiniSkill;
  title: string;
  stem: string;
  options: string[];
  correct_index: number;
  explanation: string;
  sort_order: number;
};

function drill(
  module_id: number,
  prompt_type: WritingType,
  skill: MiniSkill,
  sort_order: number,
  title: string,
  stem: string,
  options: string[],
  correct_index: number,
  explanation: string,
): SeedMiniDrill {
  return {
    slug: `unit-${module_id}-${skill}`,
    module_id,
    prompt_type,
    skill,
    title,
    stem,
    options,
    correct_index,
    explanation,
    sort_order,
  };
}

/**
 * Short Selective-style drills. Year 5–6 level: format of the text type,
 * audience, everyday punctuation, and stronger (not fancy) word choice.
 */
export const SEED_MINI_DRILLS: SeedMiniDrill[] = [
  // ── Unit 1 Narrative ──
  drill(
    1,
    'narrative',
    'format',
    1,
    'Story shape',
    'A Selective narrative usually works best when it has:',
    [
      'A clear beginning, a problem or change in the middle, and an ending',
      'Only a list of what the character ate that day',
      'A headline, a quote from a witness, and “Yours sincerely”',
    ],
    0,
    'Markers look for a story that starts, develops, and finishes. News and letter parts belong to other text types.',
  ),
  drill(
    1,
    'narrative',
    'audience',
    2,
    'Who is reading?',
    'You are writing a story for a reader who does not know the character. Which opening helps them most?',
    [
      'I went. It was good.',
      'The old gate groaned as Maya pushed it, and the garden beyond was silent.',
      'Dear Diary, today was crazy lol.',
    ],
    1,
    'The reader needs to see the scene. A diary greeting is the wrong form; a empty sentence gives them nothing.',
  ),
  drill(
    1,
    'narrative',
    'vocabulary',
    3,
    'Stronger verb',
    'Which word is a clearer choice than “went” in: “Sam went down the dark hallway”?',
    ['did', 'crept', 'stuff'],
    1,
    '“Crept” shows how Sam moved. Selective markers reward precise verbs, not rare or slangy words.',
  ),
  drill(
    1,
    'narrative',
    'punctuation',
    4,
    'Speech marks',
    'Which sentence punctuates speech correctly?',
    [
      'Help! Maya whispered.',
      '“Help!” Maya whispered.',
      '“Help! Maya whispered.',
    ],
    1,
    'Put spoken words inside speech marks, and keep the punctuation with the spoken words.',
  ),
  drill(
    1,
    'narrative',
    'structure',
    5,
    'A better opening',
    'Which first sentence is more likely to hook a Selective marker?',
    [
      'This is a story about a door.',
      'The handle had never turned before.',
      'Hi my name is Tom and I like doors.',
    ],
    1,
    'Start in the moment. Telling the reader “this is a story” wastes the opening.',
  ),

  // ── Unit 2 Diary ──
  drill(
    2,
    'diary_entry',
    'format',
    1,
    'Diary parts',
    'A diary entry for this exam should usually include:',
    [
      'A date or “Dear Diary”, first person (I), and how the writer felt',
      'A formal subject line and “Kind regards”',
      'A news headline and a quote from the principal',
    ],
    0,
    'Diary is personal and first person. Email sign-offs and news headlines are different forms.',
  ),
  drill(
    2,
    'diary_entry',
    'audience',
    2,
    'Diary voice',
    'Who is a diary mainly written for?',
    [
      'A judge in a courtroom',
      'The writer’s private self (and the exam marker reading that voice)',
      'A whole school assembly',
    ],
    1,
    'Keep the voice honest and personal. A speech voice or legal voice does not match diary.',
  ),
  drill(
    2,
    'diary_entry',
    'vocabulary',
    3,
    'Feeling words',
    'Which word shows the feeling more clearly than “sad” in: “I was sad when the robot broke”?',
    ['thing', 'disappointed', 'stuff'],
    1,
    '“Disappointed” is still simple, but more exact. Markers like precise everyday words.',
  ),
  drill(
    2,
    'diary_entry',
    'punctuation',
    4,
    'Apostrophe in I’m',
    'Which line is punctuated correctly?',
    [
      'Im so tired after the carnival.',
      'I’m so tired after the carnival.',
      'I am so tired after the carnival’.',
    ],
    1,
    'I’m = I am. The apostrophe marks the missing letter.',
  ),
  drill(
    2,
    'diary_entry',
    'structure',
    5,
    'Time order',
    'A clear diary paragraph often follows:',
    [
      'What happened, then how I felt, then what I might do next',
      'The ending first, then a shopping list',
      'Someone else’s speech with no “I” at all',
    ],
    0,
    'Diary works well in time order, with feelings attached to events.',
  ),

  // ── Unit 3 News report ──
  drill(
    3,
    'news_report',
    'format',
    1,
    'News parts',
    'A news report usually needs:',
    [
      'A headline, the key facts (who/what/where/when), and often a short quote',
      'Dear Diary and a list of feelings only',
      'Yours sincerely and a home address',
    ],
    0,
    'News is facts first. Diary and letter layouts belong to other tasks.',
  ),
  drill(
    3,
    'news_report',
    'audience',
    2,
    'Report voice',
    'Which sentence sounds like a news report, not a story about yourself?',
    [
      'I was so scared and I ran home crying.',
      'A sudden storm closed Bondi Beach this afternoon, police said.',
      'OMG you will not believe what happened!!!',
    ],
    1,
    'Reports stay calm and third-person. Save “I felt” for diary or narrative.',
  ),
  drill(
    3,
    'news_report',
    'vocabulary',
    3,
    'Report verb',
    'Which verb fits a news report better than “said” in: “The lifeguard said the water was unsafe” if you want a slightly stronger, still simple choice?',
    ['yelled forever', 'warned', 'screamed lol'],
    1,
    '“Warned” is precise and still ordinary. Slang and drama belong elsewhere.',
  ),
  drill(
    3,
    'news_report',
    'punctuation',
    4,
    'Quotes in news',
    'Which sentence quotes a speaker correctly?',
    [
      'The mayor said we will rebuild.',
      'The mayor said, “We will rebuild.”',
      'The mayor said “We will rebuild.',
    ],
    1,
    'Put the exact words in speech marks, and close them.',
  ),
  drill(
    3,
    'news_report',
    'structure',
    5,
    'Most important first',
    'In a news report, the first paragraph should usually:',
    [
      'Tell the main event in one or two clear sentences',
      'Start with the writer’s childhood',
      'Leave the main fact until the last line as a twist',
    ],
    0,
    'News is not a mystery story. Put who, what, where, when near the top.',
  ),

  // ── Unit 4 Explanation ──
  drill(
    4,
    'explanation',
    'format',
    1,
    'Explanation job',
    'An explanation text mainly:',
    [
      'Tells a made-up adventure',
      'Shows how or why something happens, in a clear order',
      'Sells a product with a slogan',
    ],
    1,
    'Explanation is “how/why”, not story and not advertisement.',
  ),
  drill(
    4,
    'explanation',
    'audience',
    2,
    'Help the reader',
    'Your reader does not already know the topic. Which sentence helps more?',
    [
      'You know what I mean.',
      'First, heat makes the magma rise. Then it finds a weak spot in the crust.',
      'It is obvious.',
    ],
    1,
    'Assume the reader needs each step. “You know what I mean” leaves them out.',
  ),
  drill(
    4,
    'explanation',
    'vocabulary',
    3,
    'Linking words',
    'Which word best links a cause and a result here: “The air cools. ___ rain falls.”',
    ['Because then wait', 'Therefore', 'Lol'],
    1,
    'Simple linking words (therefore, this means, as a result) help explanation scores.',
  ),
  drill(
    4,
    'explanation',
    'punctuation',
    4,
    'Commas in a list',
    'Which list is punctuated clearly?',
    [
      'Volcanoes need heat magma and a way out',
      'Volcanoes need heat, magma, and a way out.',
      'Volcanoes need heat magma, and a way out',
    ],
    1,
    'Use commas to separate items in a list so the reader does not trip.',
  ),
  drill(
    4,
    'explanation',
    'structure',
    5,
    'Step order',
    'A clear explanation is usually ordered:',
    [
      'From first step to last step (or cause, then effect)',
      'Random facts in any order',
      'A joke, then a diary feeling, then a headline',
    ],
    0,
    'Order is part of the structure mark. Mix-ups of form confuse the marker.',
  ),

  // ── Unit 5 Advice sheet ──
  drill(
    5,
    'advice_sheet',
    'format',
    1,
    'Advice layout',
    'An advice sheet often works well with:',
    [
      'A short welcome, clear tips (sometimes numbered), and a kind closing',
      'Only a scary story with no tips',
      'A court address and “Yours faithfully” only',
    ],
    0,
    'Advice should be easy to scan. Headings or numbered tips help the reader use it.',
  ),
  drill(
    5,
    'advice_sheet',
    'audience',
    2,
    'Friendly “you”',
    'Which tone fits advice for a new student?',
    [
      'Sit down and be quiet or else.',
      'You could join one club in the first fortnight so you meet people.',
      'Dear Sir/Madam, I remain your obedient servant.',
    ],
    1,
    'Advice is helpful and polite, not a threat and not old-fashioned letter language.',
  ),
  drill(
    5,
    'advice_sheet',
    'vocabulary',
    3,
    'Helpful verb',
    'Which is a clearer tip than “do stuff”: “___ someone at lunch on day one.”',
    ['Sit with', 'Destroy', 'Ignore forever'],
    0,
    'Choose ordinary, useful verbs. Extreme words do not fit advice.',
  ),
  drill(
    5,
    'advice_sheet',
    'punctuation',
    4,
    'Full stops in tips',
    'Which tip is a complete, correctly ended sentence?',
    [
      'Join one club in your first fortnight',
      'Join one club in your first fortnight.',
      'join one club in your first fortnight!!??',
    ],
    1,
    'Start with a capital and end with one full stop. Extra ?! looks messy.',
  ),
  drill(
    5,
    'advice_sheet',
    'structure',
    5,
    'Order of an advice sheet',
    'A sensible order is:',
    [
      'Welcome → two or three tips → a short close',
      'Close → random joke → no tips',
      'A full narrative with a twist ending',
    ],
    0,
    'Readers of advice want help quickly. Save story twists for narrative.',
  ),

  // ── Unit 6 Review ──
  drill(
    6,
    'review',
    'format',
    1,
    'Review parts',
    'A review usually includes:',
    [
      'What you are reviewing, your opinion, reasons, and a recommendation',
      'Only a plot dump of every chapter',
      'A news headline and a police quote',
    ],
    0,
    'Opinion plus reasons is the job. A report of facts without judgement is news, not a review.',
  ),
  drill(
    6,
    'review',
    'audience',
    2,
    'Who is this for?',
    'A book review for other students should mainly help them:',
    [
      'Decide whether they might like it, with fair reasons',
      'Copy your homework word for word',
      'Learn the author’s home address',
    ],
    0,
    'The reader is another student. Be useful and fair, not a spoiler dump of everything.',
  ),
  drill(
    6,
    'review',
    'vocabulary',
    3,
    'Sharper opinion word',
    'Which word is more useful than “good” in: “The ending was good”?',
    ['thingy', 'satisfying', 'stuff'],
    1,
    '“Satisfying” still sounds natural, and it tells the reader what “good” meant.',
  ),
  drill(
    6,
    'review',
    'punctuation',
    4,
    'Apostrophe for belonging',
    'Which sentence is correct?',
    [
      'The books ending surprised me.',
      'The book’s ending surprised me.',
      'The books’ ending surprised me. (one book)',
    ],
    1,
    'One book → book’s. Apostrophes show belonging, not a random extra letter.',
  ),
  drill(
    6,
    'review',
    'structure',
    5,
    'Don’t bury the opinion',
    'Where should your overall view usually appear?',
    [
      'Near the start, then explain it',
      'Never — keep it a secret',
      'Only in a tiny footnote',
    ],
    0,
    'Readers of reviews want the judgement early, then the reasons.',
  ),

  // ── Unit 7 Advertisement ──
  drill(
    7,
    'advertisement',
    'format',
    1,
    'Ad parts',
    'A short advertisement often has:',
    [
      'A catchy heading, what it offers, and a clear “what to do next”',
      'A quiet diary about your weekend',
      'A science explanation of magma only',
    ],
    0,
    'Ads need a hook, information, and a call to action (try, join, buy, visit).',
  ),
  drill(
    7,
    'advertisement',
    'audience',
    2,
    'Who are you talking to?',
    'You are advertising a school gadget to students. Which line fits?',
    [
      'Clip it to your desk and get your time back.',
      'Dear Sir, enclosed herewith the aforementioned gadget.',
      'Once upon a time there was a king.',
    ],
    0,
    'Match the reader. Formal letter English and fairy-tale openings are the wrong form.',
  ),
  drill(
    7,
    'advertisement',
    'vocabulary',
    3,
    'Persuade without shouting',
    'Which heading is strong but still suitable for a school task?',
    [
      'BUY NOW OR YOU ARE DUMB!!!!',
      'Focus has never felt this easy',
      'thing for sale',
    ],
    1,
    'Markers like controlled, lively language — not insults or all-caps shouting.',
  ),
  drill(
    7,
    'advertisement',
    'punctuation',
    4,
    'Exclamation marks',
    'Which is the better choice for Selective writing?',
    [
      'Use one exclamation mark for real energy, not after every word!',
      'Wow!!! Amazing!!! Yes!!! Now!!!',
      'Remove all full stops forever',
    ],
    0,
    'One well-placed “!” is enough. A row of them looks uncontrolled.',
  ),
  drill(
    7,
    'advertisement',
    'structure',
    5,
    'Call to action',
    'A clear ending for an ad is:',
    [
      'Ask for yours at the office today.',
      'The end of my story about a dragon.',
      'Yours faithfully, a mystery shopper.',
    ],
    0,
    'Tell the reader what to do next. That is the advertisement’s last job.',
  ),

  // ── Unit 8 Persuasive text ──
  drill(
    8,
    'persuasive_text',
    'format',
    1,
    'Argument shape',
    'A persuasive text usually needs:',
    [
      'Your position, reasons, a look at the other side, and a firm ending',
      'Only jokes and no opinion',
      'A recipe with grams and minutes',
    ],
    0,
    'Take a side, support it, and finish clearly. Sitting on the fence scores weakly.',
  ),
  drill(
    8,
    'persuasive_text',
    'audience',
    2,
    'Convince the reader',
    'Which opening states a position clearly?',
    [
      'Homework is complicated I guess.',
      'Students should have some homework, but only if it is short and useful.',
      'Once there was a cat.',
    ],
    1,
    'Say what you think in the first lines so the marker can follow your argument.',
  ),
  drill(
    8,
    'persuasive_text',
    'vocabulary',
    3,
    'Useful linking word',
    'Which word fairly introduces the other side: “___ some people say homework steals family time.”',
    ['However,', 'Kaboom', 'Yesterdaying'],
    0,
    '“However” is a simple, useful word in persuasive writing. Invented words do not help.',
  ),
  drill(
    8,
    'persuasive_text',
    'punctuation',
    4,
    'Comma after However',
    'Which sentence is punctuated correctly?',
    [
      'However homework can still help.',
      'However, homework can still help.',
      'However homework, can still help.',
    ],
    1,
    'When “However” starts a sentence, a comma usually follows it.',
  ),
  drill(
    8,
    'persuasive_text',
    'structure',
    5,
    'One idea per paragraph',
    'A strong middle paragraph should:',
    [
      'Give one reason and a short example',
      'List ten unrelated topics in one block',
      'Copy the other side with no comment',
    ],
    0,
    'Structure marks improve when each paragraph has a job.',
  ),

  // ── Unit 9 Formal letter ──
  drill(
    9,
    'formal_letter',
    'format',
    1,
    'Letter layout',
    'A formal letter should include:',
    [
      'A greeting such as Dear …, a clear purpose, and a sign-off such as Yours sincerely',
      'Dear Diary and a nickname only',
      'A huge slogan and a price',
    ],
    0,
    'Greeting + purpose + polite ending is the skeleton of a formal letter.',
  ),
  drill(
    9,
    'formal_letter',
    'audience',
    2,
    'Polite to the reader',
    'You are writing to the local council. Which line is appropriate?',
    [
      'Hey you, fix the park now or else.',
      'I am writing to ask if the broken lights in Green Street park can be repaired.',
      'Sup council, park = bad.',
    ],
    1,
    'Be direct and polite. Insults and slang miss the audience mark.',
  ),
  drill(
    9,
    'formal_letter',
    'vocabulary',
    3,
    'Letter opening phrase',
    'Which opening is the best fit for a formal letter?',
    [
      'I am writing to…',
      'Guess what!!!!',
      'Once upon a time…',
    ],
    0,
    '“I am writing to…” tells the purpose at once. Story and chat openings are the wrong form.',
  ),
  drill(
    9,
    'formal_letter',
    'punctuation',
    4,
    'Greeting comma',
    'Which greeting is punctuated in a standard way?',
    [
      'Dear Mr Chen',
      'Dear Mr Chen,',
      'Dear Mr Chen!!!!',
    ],
    1,
    'A comma after the name is the usual school convention: Dear Mr Chen,',
  ),
  drill(
    9,
    'formal_letter',
    'structure',
    5,
    'First paragraph job',
    'The first paragraph of a formal letter should usually:',
    [
      'State why you are writing',
      'Tell a long story with no request',
      'List your favourite foods',
    ],
    0,
    'Purpose first. Details can follow in the next paragraph.',
  ),

  // ── Unit 10 Speech ──
  drill(
    10,
    'speech',
    'format',
    1,
    'Speech parts',
    'A school speech usually needs:',
    [
      'A greeting to listeners, two or three points, and a thank-you ending',
      'A subject line and an email sign-off only',
      'A newspaper headline and no “you”',
    ],
    0,
    'Speeches are spoken to people in the room. Email and news layouts do not match.',
  ),
  drill(
    10,
    'speech',
    'audience',
    2,
    'Talk to listeners',
    'Which line sounds like a speech to students?',
    [
      'We can keep the oval tidy if we each take one small job.',
      'Yours sincerely, the management.',
      'Magma rises because it is hot. The end.',
    ],
    0,
    'Use we/you and a real audience. Letter endings and textbook facts are other forms.',
  ),
  drill(
    10,
    'speech',
    'vocabulary',
    3,
    'Spoken but clear',
    'Which phrase fits a speech better than “stuff is bad”?',
    ['Litter spoils our oval', 'Thingy yeah nah', 'Error 404'],
    0,
    'Keep it speakable and exact. Vague slang does not lift the vocabulary mark.',
  ),
  drill(
    10,
    'speech',
    'punctuation',
    4,
    'A question to the crowd',
    'Which question is punctuated correctly?',
    [
      'Have we done enough for our oval',
      'Have we done enough for our oval?',
      'Have we done enough for our oval.',
    ],
    1,
    'Questions need a question mark. Speeches often use a short question to involve listeners.',
  ),
  drill(
    10,
    'speech',
    'structure',
    5,
    'Open and close',
    'A solid speech pattern is:',
    [
      'Hook or greeting → points → thank the listeners',
      'Middle only, no hello and no ending',
      'A diary date, then a shopping list',
    ],
    0,
    'Listeners need a start they can hear and a clear finish.',
  ),

  // ── Unit 11 Email ──
  drill(
    11,
    'email',
    'format',
    1,
    'Email parts',
    'A school email should usually have:',
    [
      'A short subject line, a greeting, the purpose, and a simple sign-off',
      'Dear Diary and no subject',
      'A full home address at the top like a posted letter, and nothing else',
    ],
    0,
    'Subject + greeting + message + sign-off (for example Kind regards) is the email form.',
  ),
  drill(
    11,
    'email',
    'audience',
    2,
    'Teacher or friend',
    'You are emailing a teacher. Which greeting fits?',
    [
      'Hey!!!!',
      'Dear Ms Lee,',
      'Yo teach',
    ],
    1,
    'Match the reader. A teacher email stays polite; a friend message can be warmer.',
  ),
  drill(
    11,
    'email',
    'vocabulary',
    3,
    'Polite request',
    'Which is the better request?',
    [
      'Give me the notes now.',
      'Could you please send last week’s notes?',
      'Notes. Now. Thanks not.',
    ],
    1,
    '“Could you please…” is still simple English, and it fits a teacher audience.',
  ),
  drill(
    11,
    'email',
    'punctuation',
    4,
    'Subject line',
    'Which subject line is clear and correctly written?',
    [
      'help',
      'Request for last week’s science notes',
      'HELP HELP HELP HELP',
    ],
    1,
    'A subject line is a short label, with a capital at the start — not a shout.',
  ),
  drill(
    11,
    'email',
    'structure',
    5,
    'Purpose first',
    'After the greeting, the first sentence of an email should usually:',
    [
      'Say why you are writing',
      'Tell a long story with no request',
      'Paste a whole narrative task',
    ],
    0,
    'Busy readers (and markers) look for the purpose immediately.',
  ),
];

export function markMiniChoice(
  correctIndex: number,
  answerIndex: number,
): boolean {
  return Number(answerIndex) === Number(correctIndex);
}
