import {
  EARLY_MATH_UNITS,
  type EarlyMathDifficulty,
  type EarlyMathItem,
  type EarlyMathKind,
  type EarlyMathSkill,
  type MathStimulus,
} from './early-math';

type Draft = {
  slug: string;
  unitId: number;
  skill: EarlyMathSkill;
  kind?: EarlyMathKind;
  title: string;
  stem: string;
  stimulus?: MathStimulus;
  options?: string[];
  correctIndex?: number;
  accepted?: string[];
  explanation: string;
  parentPrompt: string;
  difficulty?: EarlyMathDifficulty;
};

function choice(
  draft: Draft & { options: string[]; correctIndex: number },
): Draft {
  return { kind: 'choice', ...draft };
}

function count(draft: Draft & { accepted: string[] }): Draft {
  return { kind: 'count', ...draft };
}

function yesNo(draft: Draft & { yes: boolean }): Draft {
  return {
    kind: 'true_false',
    options: ['Yes', 'No'],
    correctIndex: draft.yes ? 0 : 1,
    ...draft,
  };
}

const DRAFTS: Draft[] = [
  // ───────── Unit 1 · See the number ─────────
  choice({
    slug: 'see-dice-four',
    unitId: 1,
    skill: 'subitise-perceptual',
    title: 'Dice four',
    stem: 'How many dots are on this dice face? Try to see it, not count one by one.',
    stimulus: { type: 'dots', layout: 'dice', count: 4 },
    options: ['3', '4', '5', '6'],
    correctIndex: 1,
    explanation: 'A dice four is a square of dots. That pattern is 4.',
    parentPrompt: 'Cover the dice for a second, then uncover it. Ask “How many?” before they start pointing.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'see-scattered-three',
    unitId: 1,
    skill: 'subitise-perceptual',
    title: 'Three in a mess',
    stem: 'These counters are not in a line. How many are there?',
    stimulus: { type: 'dots', layout: 'scattered', count: 3, seed: 11 },
    accepted: ['3', 'three'],
    explanation: 'Three is a small amount you can see at once, even when the dots are not lined up.',
    parentPrompt: 'Ask whether lining them up would change how many there are.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'see-one-hand-five',
    unitId: 1,
    skill: 'subitise-structured',
    title: 'A full hand',
    stem: 'One hand is open. How many fingers is that?',
    stimulus: { type: 'fingers', left: 5, right: 0 },
    accepted: ['5', 'five'],
    explanation: 'A full hand is a 5-pattern. You do not need to count 1, 2, 3, 4, 5 every time.',
    parentPrompt: 'Hold up your own hand and hide it, then flash it. Can they still say five?',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'see-ten-frame-six',
    unitId: 1,
    skill: 'subitise-structured',
    title: 'Six on a ten-frame',
    stem: 'The ten-frame has a full five on the top row, and one more underneath. How many counters?',
    stimulus: { type: 'tenFrame', filled: 6 },
    options: ['5', '6', '7', '10'],
    correctIndex: 1,
    explanation: 'Five on the top row plus one more is 6. The empty boxes are the leftover spaces to 10.',
    parentPrompt: 'Ask “What do you see first — the five, or the extra one?”',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'see-dice-six',
    unitId: 1,
    skill: 'subitise-structured',
    title: 'Dice six',
    stem: 'This dice face has two rows of three. How many dots?',
    stimulus: { type: 'dots', layout: 'dice', count: 6 },
    options: ['4', '5', '6', '8'],
    correctIndex: 2,
    explanation: 'Two groups of 3 make 6. That is why a dice six is easy to see.',
    parentPrompt: 'Ask them to show another way to make 6 with fingers.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'see-pairs-four',
    unitId: 1,
    skill: 'subitise-conceptual',
    title: 'Two and two',
    stem: 'The dots are in pairs. How many dots altogether?',
    stimulus: { type: 'dots', layout: 'pairs', count: 4 },
    accepted: ['4', 'four'],
    explanation: 'Two pairs is 2 and 2, which is 4. Seeing pairs is faster than counting each dot.',
    parentPrompt: 'Ask “Did you count 1-2-3-4, or did you see two groups?”',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'see-which-faster-five',
    unitId: 1,
    skill: 'subitise-structured',
    title: 'A full five',
    stem: 'The top row of the ten-frame is full. How many counters is that?',
    stimulus: { type: 'tenFrame', filled: 5 },
    options: ['4', '5', '6', '10'],
    correctIndex: 1,
    explanation: 'A full top row is 5. You can see the five without counting each box.',
    parentPrompt: 'Flash the frame, then hide it. Can they still say five?',
    difficulty: 'kindy',
  }),
  count({
    slug: 'see-fingers-seven',
    unitId: 1,
    skill: 'subitise-conceptual',
    title: 'Five and two fingers',
    stem: 'One hand shows 5. The other hand shows 2. How many fingers altogether?',
    stimulus: { type: 'fingers', left: 5, right: 2 },
    accepted: ['7', 'seven'],
    explanation: '5 and 2 make 7. You can see the parts instead of counting from 1.',
    parentPrompt: 'Flash the two hands, then hide them. Can they still say 7?',
    difficulty: 'core',
  }),
  choice({
    slug: 'see-domino-eight',
    unitId: 1,
    skill: 'subitise-conceptual',
    title: 'Domino double four',
    stem: 'This domino shows 4 on each side. How many dots on the whole tile?',
    stimulus: { type: 'dots', layout: 'domino', count: 8 },
    options: ['4', '6', '8', '10'],
    correctIndex: 2,
    explanation: '4 and 4 make 8. Double 4 is a useful pattern for later number facts.',
    parentPrompt: 'Ask “If one side was 3 instead, what would the whole tile be?”',
    difficulty: 'core',
  }),
  choice({
    slug: 'see-odd-one-not-four',
    unitId: 1,
    skill: 'subitise-perceptual',
    title: 'Which is not four?',
    stem: 'Three pictures show 4. One does not. Which amount is not 4?',
    stimulus: {
      type: 'oddOneOut',
      items: [
        { icon: 'star', count: 5 },
        { icon: 'button', count: 4 },
        { icon: 'apple', count: 4 },
        { icon: 'shoe', count: 4 },
      ],
    },
    options: ['5 stars', '4 buttons', '4 apples', '4 shoes'],
    correctIndex: 0,
    explanation: 'A dice five has 5 dots. The others are all 4, shown in different ways.',
    parentPrompt: 'Make 4 with blocks, then add one. Talk about how it stopped being 4.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'see-zero-empty-frame',
    unitId: 1,
    skill: 'cardinality',
    title: 'Nothing on the frame',
    stem: 'The ten-frame has no counters. How many counters are there?',
    stimulus: { type: 'tenFrame', filled: 0 },
    accepted: ['0', 'zero', 'none'],
    explanation: 'Zero means none. An empty frame still matters, because it is the start of the count.',
    parentPrompt: 'Ask where zero sits on a number track — before 1.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'see-two-dice-five',
    unitId: 1,
    skill: 'subitise-conceptual',
    title: 'Two dice make five',
    stem: 'One dice shows 2. The other shows 3. How many dots altogether?',
    stimulus: { type: 'dots', layout: 'dice', count: 2, second: 3 },
    options: ['4', '5', '6', '23'],
    correctIndex: 1,
    explanation: '2 and 3 make 5. Do not read the dice as the number 23 — they are two amounts to combine.',
    parentPrompt: 'Watch for “twenty-three”. That mix-up is common when digits sit side by side.',
    difficulty: 'core',
  }),

  // ───────── Unit 2 · Count and compare ─────────
  yesNo({
    slug: 'count-same-line-or-spread',
    unitId: 2,
    skill: 'conservation',
    title: 'Spread out, still eight?',
    stem: 'Eight shoes in a tight line were spread across the verandah. Are there still 8 shoes?',
    stimulus: {
      type: 'groups',
      groups: [
        { count: 8, icon: 'shoe', label: 'In a line' },
        { count: 8, icon: 'shoe', label: 'Spread out' },
      ],
    },
    yes: true,
    explanation:
      'Spreading objects out does not change how many there are. The amount stays 8 unless some shoes are added or taken away.',
    parentPrompt: 'Line up 8 spoons, then spread them. Ask before they recount.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'count-on-from-six',
    unitId: 2,
    skill: 'count-on',
    title: 'Six already in the tin',
    stem: 'Start on 6. Jump forward 3 hops. What number do you land on?',
    stimulus: {
      type: 'numberLineHops',
      min: 0,
      max: 10,
      start: 6,
      hops: 3,
      blank: 'result',
    },
    accepted: ['9', 'nine'],
    explanation: 'Start at 6. Hop 7, 8, 9. 6 + 3 = 9.',
    parentPrompt: 'Cover the 6 and only let them count the 3 hops: “7, 8, 9”.',
    difficulty: 'core',
  }),
  choice({
    slug: 'count-more-without-counting',
    unitId: 2,
    skill: 'compare-collections',
    title: 'Taller stack, more blocks?',
    stem: 'Look at the two stacks. Which stack has more blocks?',
    stimulus: { type: 'compareBars', a: 9, b: 4, aLabel: 'Red', bLabel: 'Blue' },
    options: ['Red', 'Blue', 'Same', 'Cannot tell'],
    correctIndex: 0,
    explanation: 'The red row has 9. The blue row has 4. 9 is more than 4.',
    parentPrompt: 'Ask “How do you know?” The longer row is more, not heavier.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'count-order-three-numbers',
    unitId: 2,
    skill: 'order-numbers',
    title: 'Class numbers in order',
    stem: 'The roll has 9, 4 and 12. Which list goes from smallest to biggest?',
    stimulus: { type: 'pattern', items: ['9', '4', '12'], blankIndex: -1 },
    options: ['9, 12, 4', '4, 9, 12', '12, 9, 4', '4, 12, 9'],
    correctIndex: 1,
    explanation: '4 is smallest, then 9, then 12. Ordering is not the same as reading the numbers in the order they were said.',
    parentPrompt: 'Put number cards 4, 9 and 12 on the table and let them slide them.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'count-thirteen-not-thirty',
    unitId: 2,
    skill: 'teen-vs-ten',
    title: 'Thirteen or thirty?',
    stem: 'A sports-day scoreboard shows 13. Which sentence is true?',
    stimulus: { type: 'giantNumber', value: 13 },
    options: ['10 and 3', 'Same as 30', '3 tens', 'After 30'],
    correctIndex: 0,
    explanation: '13 is a teen: one ten and three ones. 30 is three tens. They sound alike but they are different sizes.',
    parentPrompt: 'Say both words slowly: thir-TEEN versus thir-TY. Show 13 and 30 on a number chart.',
    difficulty: 'core',
  }),
  count({
    slug: 'count-after-eighteen',
    unitId: 2,
    skill: 'before-after',
    title: 'The number after 18',
    stem: 'What number comes straight after 18 when you count forwards?',
    stimulus: { type: 'numberTrack', min: 15, max: 21, highlight: 18, ask: 'after' },
    accepted: ['19', 'nineteen'],
    explanation: 'After 18 is 19, then 20. “Number after” means one more, not ten more.',
    parentPrompt: 'If they say 20, they jumped. Walk one step on a number track.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'count-before-eleven',
    unitId: 2,
    skill: 'before-after',
    title: 'The number before 11',
    stem: 'What number comes just before 11?',
    stimulus: { type: 'numberTrack', min: 8, max: 14, highlight: 11, ask: 'before' },
    accepted: ['10', 'ten'],
    explanation: 'The number before 11 is 10. That is one less, and it is also one full ten.',
    parentPrompt: 'Count backwards from 14 to feel “before”.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'count-missing-seven',
    unitId: 2,
    skill: 'before-after',
    title: 'Hole in the track',
    stem: 'A number has fallen off this track. What number is missing?',
    stimulus: { type: 'numberTrack', min: 1, max: 10, missing: [7] },
    accepted: ['7', 'seven'],
    explanation: 'The track goes 6, then a gap, then 8. The missing number is 7.',
    parentPrompt: 'Ask them to whisper the whole sequence, then stop at the gap.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'count-missing-fourteen',
    unitId: 2,
    skill: 'before-after',
    title: 'Gap after thirteen',
    stem: 'The numbers go 12, 13, then a gap, then 15, 16. What number is missing?',
    stimulus: { type: 'numberLine', min: 12, max: 16, missing: [14] },
    options: ['19', '14', '11', '17'],
    correctIndex: 1,
    explanation: 'After 13 comes 14, then 15. The gap is 14, not 19 or 17.',
    parentPrompt: 'If they pick 19 they jumped too far. Walk one step from 13.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'count-ordinal-third',
    unitId: 2,
    skill: 'ordinal',
    title: 'Third in line',
    stem: 'Children line up for the slide: Mia, Sam, Ali, then Ben. Who is third?',
    stimulus: { type: 'lineup', names: ['Mia', 'Sam', 'Ali', 'Ben'] },
    options: ['Mia', 'Sam', 'Ali', 'Ben'],
    correctIndex: 2,
    explanation: 'First is Mia, second is Sam, third is Ali. Ordinal numbers are about place in a line, not how many children there are.',
    parentPrompt: 'Make a line of four toys and ask for first, second, last.',
    difficulty: 'kindy',
  }),
  yesNo({
    slug: 'count-last-number-is-total',
    unitId: 2,
    skill: 'cardinality',
    title: 'Last word of the count',
    stem: 'You count a row of bags: “1, 2, 3, 4, 5.” Does that mean there are 5 bags in the row?',
    stimulus: { type: 'groups', groups: [{ count: 5, icon: 'bag', label: '1  2  3  4  5' }] },
    yes: true,
    explanation: 'The last number you say is the total. You do not add 1+2+3+4+5.',
    parentPrompt: 'If they think the total is 15, they added the counting words. Recount and tap the last bag.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'count-compare-eleven-eight',
    unitId: 2,
    skill: 'compare-collections',
    title: 'Eleven and eight',
    stem: 'The lost-property box has 11 hats. The hook has 8. Which is true?',
    stimulus: {
      type: 'howManyMore',
      left: { count: 11, label: 'Box', icon: 'hat' },
      right: { count: 8, label: 'Hook', icon: 'hat' },
    },
    options: ['11 is more', '8 is more', 'Same', 'Cannot tell'],
    correctIndex: 0,
    explanation: '11 is one ten and one more. 8 is still less than ten, so 11 is more.',
    parentPrompt: 'Build both amounts with blocks so the extra 3 hats are visible.',
    difficulty: 'core',
  }),
  count({
    slug: 'count-back-from-ten',
    unitId: 2,
    skill: 'count-on',
    title: 'Count back from 10',
    stem: 'Count backwards: 10, 9, 8, 7. What comes next?',
    stimulus: { type: 'pattern', items: ['10', '9', '8', '7', '?'], blankIndex: 4 },
    accepted: ['6', 'six'],
    explanation: 'Counting backwards is one less each time: 10, 9, 8, 7, 6.',
    parentPrompt: 'Use a rocket countdown, then ask what number would come after 6 if you kept going down.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'count-one-to-one-keep-track',
    unitId: 2,
    skill: 'count-one-to-one',
    title: 'Do not skip a peg',
    stem: 'When you count the washing pegs, what should you do?',
    stimulus: { type: 'groups', groups: [{ count: 6, icon: 'peg', label: 'Pegs' }] },
    options: ['Touch each once', 'Say numbers fast', 'Count some twice', 'Stop at 5'],
    correctIndex: 0,
    explanation: 'One-to-one means one pointing action for one counting word. Skipping or double-counting changes the total.',
    parentPrompt: 'Watch their finger. If it races ahead of the words, slow them down.',
    difficulty: 'kindy',
  }),

  // ───────── Unit 3 · Parts of 10 ─────────
  count({
    slug: 'parts-full-ten-frame',
    unitId: 3,
    skill: 'ten-bonds',
    title: 'A full ten-frame',
    stem: 'Every box in the ten-frame has a counter. How many counters is that?',
    stimulus: { type: 'tenFrame', filled: 10 },
    accepted: ['10', 'ten'],
    explanation: 'A full ten-frame is 10. Two rows of 5 also make 10.',
    parentPrompt: 'Empty one counter and ask how many now, and how many spaces.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'parts-seven-is-five-two',
    unitId: 3,
    skill: 'five-wise',
    title: 'Seven hiding five',
    stem: '5 and a missing number make 7. What number is missing?',
    stimulus: { type: 'numberSentence', a: 5, op: '+', b: null, result: 7 },
    options: ['2', '3', '4', '5'],
    correctIndex: 0,
    explanation: '5 and 2 make 7. Count on from 5: 6, 7.',
    parentPrompt: 'Show a hand of 5 plus 2 fingers. Hide the 2 and ask again.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'parts-make-ten-from-six',
    unitId: 3,
    skill: 'missing-part',
    title: 'Make ten from six',
    stem: 'The ten-frame shows 6. How many more counters fill the frame?',
    stimulus: { type: 'tenFrame', filled: 6 },
    accepted: ['4', 'four'],
    explanation: '6 and 4 make 10. The four empty boxes are the missing part.',
    parentPrompt: 'Do not let them recount all 10 unless they need to. Point at the empty boxes.',
    difficulty: 'core',
  }),
  choice({
    slug: 'parts-eight-from-ten',
    unitId: 3,
    skill: 'part-whole',
    title: 'Eight from a ten',
    stem: 'There were 10 library cards. 2 have a cross. How many cards are left?',
    stimulus: {
      type: 'groups',
      groups: [{ count: 10, icon: 'book', label: 'Library cards', crossed: 2 }],
    },
    options: ['8', '12', '2', '10'],
    correctIndex: 0,
    explanation: '10 take away 2 is 8. Count the cards that do not have a cross.',
    parentPrompt: 'If they say 12, they added. Point to the cards that are still there.',
    difficulty: 'core',
  }),
  choice({
    slug: 'parts-same-as-five-two',
    unitId: 3,
    skill: 'part-whole',
    title: 'Same as 5 and 2',
    stem: '5 + 2 = 7. Which other number sentence also makes 7?',
    stimulus: { type: 'numberSentence', a: 5, op: '+', b: 2, result: 7 },
    options: ['4 + 3', '5 + 5', '2 + 2', '7 + 2'],
    correctIndex: 0,
    explanation: '5 + 2 and 4 + 3 are both 7. The parts look different, but they make the same total.',
    parentPrompt: 'Build both on ten-frames and slide them side by side.',
    difficulty: 'core',
  }),
  count({
    slug: 'parts-missing-on-bond',
    unitId: 3,
    skill: 'missing-part',
    title: 'The empty part of 10',
    stem: '3 and a missing number make 10. What number is missing?',
    stimulus: { type: 'numberSentence', a: 3, op: '+', b: null, result: 10 },
    accepted: ['7', 'seven'],
    explanation: '3 and 7 make 10. Count on from 3 until you reach 10.',
    parentPrompt: 'Show 10 fingers, then fold down 3. The fingers still up are 7.',
    difficulty: 'core',
  }),
  choice({
    slug: 'parts-five-and-friends',
    unitId: 3,
    skill: 'five-wise',
    title: 'Nine with a five',
    stem: 'How can you see 9 on a ten-frame without counting from 1?',
    stimulus: { type: 'tenFrame', filled: 9 },
    options: ['5 and 4 more', '10 and 1 more', '2 and 9', 'Count every box'],
    correctIndex: 0,
    explanation: '9 is 5 and 4, or 10 take 1. Both beat counting nine ones.',
    parentPrompt: 'Cover the top row and ask what is left underneath.',
    difficulty: 'kindy',
  }),
  yesNo({
    slug: 'parts-six-and-four-ten',
    unitId: 3,
    skill: 'ten-bonds',
    title: 'Do 6 and 4 make 10?',
    stem: 'Is 6 + 4 the same as 10?',
    stimulus: { type: 'tenFrame', filled: 10 },
    yes: true,
    explanation: '6 and 4 are a ten-bond. 7 and 3, 8 and 2, 9 and 1, and 5 and 5 are the other pairs.',
    parentPrompt: 'Ask for a different pair that also makes 10.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'parts-see-the-parts',
    unitId: 3,
    skill: 'part-whole',
    title: 'Parts of eight',
    stem: 'The top circle is all 8. The two parts are 5 and 3. Which number sentence matches?',
    stimulus: {
      type: 'partWhole',
      whole: 8,
      left: 5,
      right: 3,
      wholeLabel: 'All',
      leftLabel: 'Part',
      rightLabel: 'Part',
    },
    options: ['5 + 3 = 8', '5 + 8 = 3', '8 − 5 = 8', '3 + 3 = 8'],
    correctIndex: 0,
    explanation: 'The two parts 5 and 3 make the all: 5 + 3 = 8.',
    parentPrompt: 'Point All, then each Part, then say the sentence out loud.',
    difficulty: 'core',
  }),
  choice({
    slug: 'parts-both-of-five',
    unitId: 3,
    skill: 'part-whole',
    title: 'Two parts of five',
    stem: 'Here are 5 counters. Which pair of parts makes 5?',
    stimulus: { type: 'dots', layout: 'line', count: 5 },
    options: ['2 and 3', '4 and 4', '5 and 5', '1 and 5'],
    correctIndex: 0,
    explanation: '2 and 3 make 5. 1 and 5 make 6, so that pair is too big.',
    parentPrompt: 'Have them show another pair for 5, such as 4 and 1.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'parts-double-four',
    unitId: 3,
    skill: 'part-whole',
    title: 'Double four',
    stem: '4 on this side of the domino, 4 on the other. What is the whole?',
    stimulus: { type: 'dots', layout: 'domino', count: 8 },
    accepted: ['8', 'eight'],
    explanation: 'A double is two equal parts. Double 4 is 8.',
    parentPrompt: 'Ask double 5 as a stretch if this felt easy.',
    difficulty: 'core',
  }),
  choice({
    slug: 'parts-ten-ones-one-ten',
    unitId: 3,
    skill: 'tens-ones',
    title: 'Ten ones become a ten',
    stem: 'You have 10 loose ones. What is another name for that amount?',
    stimulus: { type: 'baseTen', tens: 0, ones: 10 },
    options: ['1 ten', '10 tens', '0', '100'],
    correctIndex: 0,
    explanation: 'Ten ones can be bundled as 1 ten. That idea is the door into place value.',
    parentPrompt: 'Bundle 10 sticks or pencils with a rubber band.',
    difficulty: 'core',
  }),

  // ───────── Unit 4 · Put together, take away (CGI types) ─────────
  count({
    slug: 'story-join-result-mat',
    unitId: 4,
    skill: 'join-result',
    title: 'Children join the mat',
    stem: '4 children are on the mat. 3 more come from painting. How many children are on the mat now?',
    stimulus: { type: 'groups', groups: [
      { count: 4, icon: 'child', label: 'On the mat' },
      { count: 3, icon: 'child', label: '3 more' },
    ] },
    accepted: ['7', 'seven'],
    explanation: '4 children and 3 more make 7.',
    parentPrompt: 'Act it with toys walking onto a mat.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'story-join-change-library',
    unitId: 4,
    skill: 'join-change',
    title: 'Books added to the display',
    stem: 'The display started on 6. Now it is 9. How many were added?',
    stimulus: {
      type: 'numberLineHops',
      min: 0,
      max: 10,
      start: 6,
      end: 9,
      blank: 'hops',
    },
    accepted: ['3', 'three'],
    explanation: 'Start at 6. Hop to 9. That is 3 hops. 6 + 3 = 9.',
    parentPrompt: 'If they say 15, they added 6 and 9. Count the hops: 7, 8, 9.',
    difficulty: 'core',
  }),
  count({
    slug: 'story-join-start-hats',
    unitId: 4,
    skill: 'join-start',
    title: 'Spare hats in the crate',
    stem: 'Some hats were already there. 4 more went in. Now there are 7. How many were there at the start?',
    stimulus: { type: 'numberSentence', a: null, op: '+', b: 4, result: 7 },
    accepted: ['3', 'three'],
    explanation: '□ + 4 = 7. 3 + 4 = 7, so the start was 3.',
    parentPrompt: 'This is harder than “how many now”. Hide 3 hats, then add 4.',
    difficulty: 'stretch',
  }),
  count({
    slug: 'story-separate-result-lunch',
    unitId: 4,
    skill: 'separate-result',
    title: 'Lunch orders eaten',
    stem: 'There were 9 lunch boxes. 3 have a cross. How many boxes are left?',
    stimulus: {
      type: 'groups',
      groups: [{ count: 9, icon: 'box', label: 'Lunch boxes', crossed: 3 }],
    },
    accepted: ['6', 'six'],
    explanation: '9 take away 3 is 6. Count the boxes that do not have a cross.',
    parentPrompt: 'Cross off 3 on a drawing of 9 boxes.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'story-separate-change-pencils',
    unitId: 4,
    skill: 'separate-change',
    title: 'Pencils that broke',
    stem: 'There were 10 pencils. Some broke. 6 are still left. How many broke?',
    stimulus: { type: 'numberSentence', a: 10, op: '-', b: null, result: 6 },
    accepted: ['4', 'four'],
    explanation: '10 − □ = 6. 10 take away 4 is 6, so 4 broke.',
    parentPrompt: 'If they say 16, they added. Put out 10 pencils and hide until 6 remain.',
    difficulty: 'core',
  }),
  count({
    slug: 'story-separate-start-boots',
    unitId: 4,
    skill: 'separate-start',
    title: 'Rain boots by the door',
    stem: 'Some boots were by the door. 2 were taken. 5 are still there. How many were there at the start?',
    stimulus: { type: 'numberSentence', a: null, op: '-', b: 2, result: 5 },
    accepted: ['7', 'seven'],
    explanation: '□ − 2 = 5. 7 take away 2 is 5, so the start was 7.',
    parentPrompt: 'Put 5 boots out, then bring 2 back. That rebuilds the start.',
    difficulty: 'stretch',
  }),
  count({
    slug: 'story-ppw-whole-cones',
    unitId: 4,
    skill: 'ppw-whole',
    title: 'Red and yellow cones',
    stem: 'There are 5 red cones and 4 yellow cones. How many cones altogether?',
    stimulus: { type: 'groups', groups: [
      { count: 5, icon: 'cone', label: 'Red' },
      { count: 4, icon: 'cone', label: 'Yellow' },
    ] },
    accepted: ['9', 'nine'],
    explanation: '5 red and 4 yellow make 9 cones altogether.',
    parentPrompt: 'Count the red, then keep counting the yellow.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'story-ppw-part-jobs',
    unitId: 4,
    skill: 'ppw-part',
    title: 'Jobs on the roster',
    stem: 'There are 8 jobs. 3 are wiping tables. How many jobs are left for packing bags?',
    stimulus: { type: 'numberSentence', a: 3, op: '+', b: null, result: 8 },
    accepted: ['5', 'five'],
    explanation: '3 + □ = 8. 3 and 5 make 8.',
    parentPrompt: 'If they say 11, they added 8 and 3. Count on from 3 to 8.',
    difficulty: 'core',
  }),
  count({
    slug: 'story-compare-difference-stickers',
    unitId: 4,
    skill: 'compare-difference',
    title: 'Mia’s extra stickers',
    stem: 'Mia has 7 merit stickers. Tom has 4. How many more stickers does Mia have than Tom?',
    stimulus: { type: 'compareBars', a: 7, b: 4, aLabel: 'Mia', bLabel: 'Tom' },
    accepted: ['3', 'three'],
    explanation: 'Compare stories ask for the difference. Match 4 to 4, and 3 stickers stick out.',
    parentPrompt: 'Line the stickers in two rows. The leftover row is the answer, not Mia’s total.',
    difficulty: 'core',
  }),
  count({
    slug: 'story-compare-quantity-bus',
    unitId: 4,
    skill: 'compare-quantity',
    title: 'Ali has two more',
    stem: 'Sam has 4 seats saved. Ali has 2 more seats than Sam. How many seats did Ali save?',
    stimulus: {
      type: 'groups',
      groups: [
        { count: 4, icon: 'block', label: 'Sam' },
        { count: 2, icon: 'block', label: '2 more for Ali' },
      ],
    },
    accepted: ['6', 'six'],
    explanation: 'Ali’s amount is unknown: Sam’s 4 plus 2 more is 6. “2 more than” does not mean the answer is 2.',
    parentPrompt: 'Build Sam’s 4, then add 2 beside them for Ali.',
    difficulty: 'stretch',
  }),
  count({
    slug: 'story-match-the-action',
    unitId: 4,
    skill: 'join-result',
    title: 'Seven and three hops',
    stem: 'Start on 7. Jump forward 3 hops. What number do you land on?',
    stimulus: {
      type: 'numberLineHops',
      min: 0,
      max: 10,
      start: 7,
      hops: 3,
      blank: 'result',
    },
    accepted: ['10', 'ten'],
    explanation: 'Start at 7. Hop 8, 9, 10. 7 + 3 = 10.',
    parentPrompt: 'Let them tap each hop and say the next number.',
    difficulty: 'kindy',
  }),
  yesNo({
    slug: 'story-same-sentence-different-parts',
    unitId: 4,
    skill: 'ppw-whole',
    title: 'Is 3 + 5 the same as 4 + 4?',
    stem: '3 red markers and 5 blue markers make 8. Is 4 + 4 also 8?',
    stimulus: {
      type: 'groups',
      groups: [
        { count: 3, icon: 'bead', label: '3 red' },
        { count: 5, icon: 'bead', label: '5 blue' },
      ],
    },
    yes: true,
    explanation: 'Different parts can make the same whole. 3 + 5 and 4 + 4 are both 8.',
    parentPrompt: 'Build both on a ten-frame and talk about “same whole, different parts”.',
    difficulty: 'core',
  }),
  count({
    slug: 'story-related-three-four',
    unitId: 4,
    skill: 'related-facts',
    title: 'The fact that matches 3 + 4',
    stem: '3 + 4 = 7. Use that fact. What number is missing in 7 − 4 = □?',
    stimulus: { type: 'relatedFacts', a: 3, b: 4, total: 7 },
    accepted: ['3', 'three'],
    explanation: '3 + 4 = 7, so 7 take away 4 leaves the other part, 3.',
    parentPrompt: 'This is a Year 1 idea. Cover 4 on a ten-frame of 7 and see 3 left.',
    difficulty: 'stretch',
  }),
  count({
    slug: 'story-three-addends-trays',
    unitId: 4,
    skill: 'three-addends',
    title: 'Three little trays',
    stem: 'The trays have 2, then 3, then 1. What is 2 + 3 + 1?',
    stimulus: { type: 'addThree', addends: [2, 3, 1], icon: 'apple' },
    accepted: ['6', 'six'],
    explanation: '2 and 3 make 5. 5 and 1 make 6.',
    parentPrompt: 'Let them add two trays first, then the last tray.',
    difficulty: 'stretch',
  }),

  // ───────── Unit 5 · Tens and ones ─────────
  choice({
    slug: 'place-twenty-four',
    unitId: 5,
    skill: 'tens-ones',
    title: 'Read 24',
    stem: 'This number is 2 tens and 4 ones. What number is it?',
    stimulus: { type: 'baseTen', tens: 2, ones: 4 },
    options: ['24', '42', '6', '204'],
    correctIndex: 0,
    explanation: '2 tens is 20, and 4 ones make 24. 42 would be 4 tens and 2 ones.',
    parentPrompt: 'Swap the tens and ones physically so 24 and 42 look different.',
    difficulty: 'core',
  }),
  count({
    slug: 'place-ten-more-thirty-six',
    unitId: 5,
    skill: 'ten-more-less',
    title: 'Ten more than 36',
    stem: 'What is 10 more than 36?',
    stimulus: { type: 'baseTen', tens: 3, ones: 6 },
    accepted: ['46', 'forty six'],
    explanation: 'Ten more adds one ten. The ones digit stays 6, so 36 becomes 46.',
    parentPrompt: 'If they say 37, they added one, not ten. Jump a row on a hundred chart.',
    difficulty: 'stretch',
  }),
  count({
    slug: 'place-ten-less-fifty',
    unitId: 5,
    skill: 'ten-more-less',
    title: 'Ten less than 50',
    stem: 'What is 10 less than 50?',
    stimulus: { type: 'giantNumber', value: 50 },
    accepted: ['40', 'forty'],
    explanation: '50 is 5 tens. Take one ten away and you have 4 tens, which is 40. Not 49.',
    parentPrompt: 'Watch for 49 (one less) or 40 written as 4.',
    difficulty: 'stretch',
  }),
  count({
    slug: 'place-skip-fives',
    unitId: 5,
    skill: 'skip-count',
    title: 'Skip count in fives',
    stem: 'The pattern is 5, 10, 15, 20, 25. What comes next?',
    stimulus: { type: 'pattern', items: ['5', '10', '15', '20', '25', '?'], blankIndex: 5 },
    accepted: ['30', 'thirty'],
    explanation: 'Skip counting in 5s lands on 30 next. Each jump is one extra five.',
    parentPrompt: 'Use a clock face or a handful of 5-cent coins if you have them.',
    difficulty: 'core',
  }),
  count({
    slug: 'place-skip-twos',
    unitId: 5,
    skill: 'skip-count',
    title: 'Pairs of sports shoes',
    stem: 'Shoes are counted in pairs: 2, 4, 6, 8. What is the next number?',
    stimulus: { type: 'pattern', items: ['2', '4', '6', '8', '?'], blankIndex: 4 },
    accepted: ['10', 'ten'],
    explanation: 'Skip counting by 2s is how we count pairs. After 8 comes 10.',
    parentPrompt: 'If they say 9, they switched to counting by ones.',
    difficulty: 'core',
  }),
  count({
    slug: 'place-skip-tens',
    unitId: 5,
    skill: 'skip-count',
    title: 'Counting in tens',
    stem: 'Count in tens: 10, 20, 30, 40. What comes next?',
    stimulus: { type: 'pattern', items: ['10', '20', '30', '40', '?'], blankIndex: 4 },
    accepted: ['50', 'fifty'],
    explanation: 'Each jump adds one ten. After 4 tens comes 5 tens, which is 50.',
    parentPrompt: 'Stack ten-sticks or draw bundles rather than chanting only.',
    difficulty: 'core',
  }),
  choice({
    slug: 'place-number-line-seventy',
    unitId: 5,
    skill: 'number-line',
    title: 'Twelve on the line',
    stem: 'The orange dot sits on this number line. Which number is it on?',
    stimulus: { type: 'numberLine', min: 0, max: 20, target: 12 },
    options: ['12', '20', '2', '10'],
    correctIndex: 0,
    explanation: 'The orange dot is on 12. 12 sits between 10 and 15.',
    parentPrompt: 'If they say 20 they read the end of the line. Point to the dot, then the number under it.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'place-add-six-twelve',
    unitId: 5,
    skill: 'count-on',
    title: 'Six and twelve',
    stem: '6 + 12 = □. Use the hops if you need them. What is the answer?',
    stimulus: {
      type: 'numberLineHops',
      min: 0,
      max: 20,
      start: 6,
      hops: 12,
      blank: 'result',
    },
    options: ['18', '20', '19', '16'],
    correctIndex: 0,
    explanation: 'Start at 6. Twelve hops land on 18. 6 + 12 = 18.',
    parentPrompt: 'Count on from 6, or jump 10 to 16 then 2 more to 18.',
    difficulty: 'core',
  }),
  choice({
    slug: 'place-thirteen-partition',
    unitId: 5,
    skill: 'tens-ones',
    title: 'Thirteen as ten and three',
    stem: 'Which shows 13?',
    stimulus: { type: 'giantNumber', value: 13 },
    options: ['1 ten and 3', '3 tens and 1', '13 tens', '1 + 3 = 4'],
    correctIndex: 0,
    explanation: '13 is one ten and three leftover ones. Adding 1 and 3 as if they were ones loses the ten.',
    parentPrompt: 'Build it with a ten-frame plus 3 extras.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'place-forty-vs-fourteen',
    unitId: 5,
    skill: 'place-zero',
    title: '40 is not 14',
    stem: 'Which number is 4 tens and 0 ones?',
    stimulus: { type: 'baseTen', tens: 4, ones: 0 },
    options: ['40', '14', '4', '400'],
    correctIndex: 0,
    explanation: 'The zero in 40 says there are no leftover ones. 14 is one ten and four ones.',
    parentPrompt: 'Write 40 and 14. Point to the zero and ask what it is doing.',
    difficulty: 'core',
  }),
  count({
    slug: 'place-count-collection-by-tens',
    unitId: 5,
    skill: 'tens-ones',
    title: 'Count a big collection',
    stem: 'The counters are already grouped: 3 tens and 4 leftover ones. How many counters?',
    stimulus: { type: 'baseTen', tens: 3, ones: 4 },
    accepted: ['34', 'thirty four'],
    explanation: 'Skip count the tens (10, 20, 30) then add the 4 ones to make 34.',
    parentPrompt: 'Refuse a 1-by-1 count if the groups of ten are already there.',
    difficulty: 'stretch',
  }),
  count({
    slug: 'place-after-twenty-nine',
    unitId: 5,
    skill: 'before-after',
    title: 'After 29',
    stem: 'What number comes after 29?',
    stimulus: { type: 'numberTrack', min: 28, max: 32, highlight: 29, ask: 'after' },
    accepted: ['30', 'thirty'],
    explanation: '29 is 2 tens and 9 ones. One more fills the next ten, so the number is 30.',
    parentPrompt: 'This is the odometer moment: ones roll from 9 to 0 and a new ten appears.',
    difficulty: 'stretch',
  }),
  choice({
    slug: 'place-odd-even-socks',
    unitId: 5,
    skill: 'skip-count',
    title: 'Odd sock or a pair?',
    stem: '7 socks are in the basket. Can they all stand in pairs with none left over?',
    stimulus: { type: 'groups', groups: [{ count: 7, icon: 'sock', label: 'Socks' }] },
    options: [
      'No, one left',
      'Yes, even',
      'Yes, 7 > 2',
      'Never pairs',
    ],
    correctIndex: 0,
    explanation: 'Even numbers make pairs with none left. 7 makes 3 pairs and one leftover, so it is odd.',
    parentPrompt: 'Pair real socks. The leftover sock is the idea of odd.',
    difficulty: 'core',
  }),
  count({
    slug: 'place-nonstandard-partition',
    unitId: 5,
    skill: 'tens-ones',
    title: 'Two tens and fifteen ones',
    stem: 'A child made 2 tens and 15 leftover ones. What number is that?',
    stimulus: { type: 'baseTen', tens: 2, ones: 15 },
    accepted: ['35', 'thirty five'],
    explanation: '15 ones is 1 ten and 5 ones. Add that extra ten to the 2 tens to make 3 tens and 5 ones: 35.',
    parentPrompt: 'Bundle 10 of the ones. This is the Year 1 stretch: numbers can be partitioned in more than one way.',
    difficulty: 'stretch',
  }),

  // ───────── Unit 6 · Everyday maths ─────────
  choice({
    slug: 'every-pattern-ab',
    unitId: 6,
    skill: 'repeating-pattern',
    title: 'Clap, stamp, clap, stamp',
    stem: 'The pattern is clap, stamp, clap, stamp, clap. What comes next?',
    stimulus: { type: 'pattern', items: ['clap', 'stamp', 'clap', 'stamp', 'clap', '?'], blankIndex: 5 },
    options: ['stamp', 'clap', 'jump', 'stop'],
    correctIndex: 0,
    explanation: 'The repeating unit is clap-stamp. After a clap comes a stamp.',
    parentPrompt: 'Do the actions. Ask them to name the unit of repeat, not just guess the next sound.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-pattern-abc',
    unitId: 6,
    skill: 'repeating-pattern',
    title: 'Bead colours',
    stem: 'Beads go red, blue, yellow, red, blue, yellow, red. What colour is next?',
    stimulus: { type: 'pattern', items: ['red', 'blue', 'yellow', 'red', 'blue', 'yellow', 'red', '?'], blankIndex: 7 },
    options: ['blue', 'red', 'yellow', 'green'],
    correctIndex: 0,
    explanation: 'The unit is red-blue-yellow. After red comes blue.',
    parentPrompt: 'If they say yellow, they are copying the last bead they notice, not the unit.',
    difficulty: 'core',
  }),
  choice({
    slug: 'every-pattern-aab',
    unitId: 6,
    skill: 'repeating-pattern',
    title: 'Two stamps then a clap',
    stem: 'The pattern is stamp, stamp, clap, stamp, stamp, clap, stamp. What comes next?',
    stimulus: { type: 'pattern', items: ['stamp', 'stamp', 'clap', 'stamp', 'stamp', 'clap', 'stamp', '?'], blankIndex: 7 },
    options: ['stamp', 'clap', 'jump', 'both'],
    correctIndex: 0,
    explanation: 'The unit is stamp-stamp-clap (AAB). After the first stamp of a new unit comes the second stamp.',
    parentPrompt: 'Circle each unit of three. AAB is harder than AB because the repeat is longer.',
    difficulty: 'stretch',
  }),
  choice({
    slug: 'every-triangle-corners',
    unitId: 6,
    skill: 'shape-2d',
    title: 'How many corners?',
    stem: 'Look at the triangle. How many corners does it have?',
    stimulus: { type: 'shapes', items: [{ kind: 'triangle', label: 'Triangle' }] },
    options: ['2', '3', '4', '0'],
    correctIndex: 1,
    explanation: 'A triangle has 3 sides and 3 corners. A square has 4.',
    parentPrompt: 'Trace the corners with a finger. Count corners, then count sides, and match them.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-not-a-square',
    unitId: 6,
    skill: 'shape-2d',
    title: 'Which is not a square?',
    stem: 'Which shape is not a square?',
    stimulus: { type: 'shapes', items: [
      { kind: 'square' },
      { kind: 'rectangle' },
      { kind: 'circle' },
    ] },
    options: ['The circle', 'The square', 'A window', 'A dice face'],
    correctIndex: 0,
    explanation: 'A circle is round, with no corners. A rectangle is not a square either, but the circle is the clear “not a square”.',
    parentPrompt: 'Talk about corners and equal sides, not only “it looks like a box”.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-sphere-rolls',
    unitId: 6,
    skill: 'shape-3d',
    title: 'What rolls?',
    stem: 'Which object rolls in every direction because it is a sphere?',
    stimulus: {
      type: 'tapPictures',
      items: [
        { icon: 'ball' },
        { icon: 'book' },
        { icon: 'box' },
        { icon: 'frame' },
      ],
    },
    options: ['Ball', 'Book', 'Box', 'Frame'],
    correctIndex: 0,
    explanation: 'A sphere is round like a ball. A box can slide, but it does not roll like a sphere.',
    parentPrompt: 'Compare a ball and a block. Ask which would be a bad building block and why.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-position-under',
    unitId: 6,
    skill: 'position',
    title: 'Bag under the bench',
    stem: 'The school bag is under the bench. Which sentence is true?',
    stimulus: { type: 'position', place: 'bench', target: 'bag' },
    options: ['Under', 'On', 'Behind', 'Inside'],
    correctIndex: 0,
    explanation: 'Under means the bag is below the bench. On would mean it is sitting on top.',
    parentPrompt: 'Move a real bag on, under, and beside a chair and ask for the word each time.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-left-of-slide',
    unitId: 6,
    skill: 'position',
    title: 'Who is on the left?',
    stem: 'You are looking at the slide. Mia is on the left. Sam is on the right. Who is on the left?',
    stimulus: { type: 'position', place: 'slide', target: 'mia' },
    options: ['Mia', 'Sam', 'The slide', 'Cannot tell'],
    correctIndex: 0,
    explanation: 'Left and right depend on the way you are facing. In this picture, Mia is on the left.',
    parentPrompt: 'Stand beside them facing the same way. Left/right from the opposite side flips.',
    difficulty: 'core',
  }),
  choice({
    slug: 'every-longer-ribbon',
    unitId: 6,
    skill: 'length-compare',
    title: 'Which ribbon is longer?',
    stem: 'Two ribbons are lined up at the same starting point. Which is longer?',
    stimulus: { type: 'compareBars', a: 8, b: 5, aLabel: 'Blue ribbon', bLabel: 'Yellow ribbon' },
    options: ['Blue', 'Yellow', 'Same', 'Yellow, thicker'],
    correctIndex: 0,
    explanation: 'Line the ends up before you compare. The blue ribbon sticks out further, so it is longer.',
    parentPrompt: 'If they pick the thicker-looking one, they mixed length with width.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-heavier-book',
    unitId: 6,
    skill: 'mass-compare',
    title: 'Which is heavier?',
    stem: 'A picture book and a feather are on a balance. The book side goes down. Which is heavier?',
    stimulus: { type: 'balance', left: 'book', right: 'feather', down: 'left' },
    options: [
      'Book',
      'Feather',
      'Same',
      'Feather, fluffy',
    ],
    correctIndex: 0,
    explanation: 'The side that goes down is heavier. Fluffy is not the same as heavy.',
    parentPrompt: 'Heft a book and a pillow. Size can trick you; mass is how heavy it feels.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-capacity-jugs',
    unitId: 6,
    skill: 'capacity-compare',
    title: 'Which jug holds more?',
    stem: 'Both jugs are full. The tall thin jug filled 2 cups. The short wide jug filled 5 cups. Which holds more?',
    stimulus: { type: 'jugs', tallCups: 2, wideCups: 5 },
    options: [
      'Short wide',
      'Tall thin',
      'Same',
      'Need a clock',
    ],
    correctIndex: 0,
    explanation: 'Capacity is how much it holds. Cups are the unit. 5 cups is more than 2, even if the jug looks shorter.',
    parentPrompt: 'This is the classic trick: taller does not always hold more.',
    difficulty: 'core',
  }),
  choice({
    slug: 'every-clock-three',
    unitId: 6,
    skill: 'time-hour',
    title: 'Three o’clock',
    stem: 'The short hand points to 3. The long hand points to 12. What time is it?',
    stimulus: { type: 'clock', hour: 3, minute: 0 },
    options: ['3 o’clock', '12 o’clock', 'Half past 3', '3:30'],
    correctIndex: 0,
    explanation: 'When the long hand is at 12, it is o’clock. The short hand names the hour: 3 o’clock.',
    parentPrompt: 'If they say 12 o’clock, they read the long hand as the hour.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-clock-half-past',
    unitId: 6,
    skill: 'time-half',
    title: 'Half past four',
    stem: 'The long hand is at 6. The short hand is halfway between 4 and 5. What time is it?',
    stimulus: { type: 'clock', hour: 4, minute: 30 },
    options: ['Half past 4', '4 o’clock', 'Half past 5', '6 o’clock'],
    correctIndex: 0,
    explanation: 'Long hand at 6 means half past. The short hand sits between 4 and 5, so it is half past 4.',
    parentPrompt: 'Year 1 stretch. Show that the hour hand moves as well, not only the minute hand.',
    difficulty: 'stretch',
  }),
  choice({
    slug: 'every-day-after-wednesday',
    unitId: 6,
    skill: 'days-sequence',
    title: 'The day after Wednesday',
    stem: 'Assembly is on Wednesday. Library is the next day. Which day is library?',
    stimulus: { type: 'dayStrip', highlight: 'Wed' },
    options: ['Thursday', 'Tuesday', 'Friday', 'Monday'],
    correctIndex: 0,
    explanation: 'The days go … Tuesday, Wednesday, Thursday… The day after Wednesday is Thursday.',
    parentPrompt: 'Sing the days, then stop at Wednesday and ask for the next word.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-morning-or-night',
    unitId: 6,
    skill: 'days-sequence',
    title: 'When do we sleep?',
    stem: 'Which event belongs to night-time?',
    stimulus: {
      type: 'tapPictures',
      items: [
        { icon: 'bed' },
        { icon: 'sand' },
        { icon: 'child' },
        { icon: 'bowl' },
      ],
    },
    options: ['Sleep', 'Recess', 'Morning circle', 'Lunch'],
    correctIndex: 0,
    explanation: 'Night is for sleeping. Recess, morning circle and lunch sit in the school day.',
    parentPrompt: 'Make a simple day strip: morning, lunchtime, afternoon, night.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-graph-most',
    unitId: 6,
    skill: 'picture-graph',
    title: 'Favourite play',
    stem: 'The class voted for favourite play. Which activity has the most votes?',
    stimulus: {
      type: 'pictureGraph',
      title: 'Our favourite play',
      rows: [
        { label: 'Sandpit', count: 6, icon: 'sand' },
        { label: 'Blocks', count: 3, icon: 'block' },
        { label: 'Bikes', count: 4, icon: 'bike' },
      ],
    },
    options: ['Sandpit', 'Blocks', 'Bikes', 'Same'],
    correctIndex: 0,
    explanation: 'Each picture stands for one vote. Sandpit has 6, bikes 4, blocks 3, so sandpit is the most.',
    parentPrompt: 'Ask “How many more chose sandpit than blocks?” as a stretch (3 more).',
    difficulty: 'core',
  }),
  count({
    slug: 'every-tally-seven',
    unitId: 6,
    skill: 'tally',
    title: 'Read the tally',
    stem: 'The tally shows a group of 5 and two more marks. How many is that?',
    stimulus: { type: 'tally', count: 7 },
    accepted: ['7', 'seven'],
    explanation: 'A tally gate of 5, plus 2 singles, is 7. The fifth mark crosses the first four.',
    parentPrompt: 'Make tallies while watching cars. Stop at 5 and cross the gate.',
    difficulty: 'core',
  }),
  choice({
    slug: 'every-chance-sunrise',
    unitId: 6,
    skill: 'chance-language',
    title: 'Will the sun come up?',
    stem: 'Tomorrow the sun will come up. Which word fits best?',
    stimulus: { type: 'groups', groups: [{ count: 1, icon: 'sun', label: 'Tomorrow' }] },
    options: ['Will', 'Might', "Won't", 'Need a dice'],
    correctIndex: 0,
    explanation: 'The sun coming up is certain — it will happen. “Might” is for things that are possible but not sure.',
    parentPrompt: 'Contrast with “It might rain” and “Pigs won’t fly into assembly”.',
    difficulty: 'core',
  }),
  count({
    slug: 'every-share-eight',
    unitId: 6,
    skill: 'sharing',
    title: 'Share the counters',
    stem: 'Share 8 counters equally between 2 children. How many does each child get?',
    stimulus: { type: 'sharing', total: 8, people: 2 },
    accepted: ['4', 'four'],
    explanation: 'Equal sharing means the same number each. 8 split into 2 equal groups is 4 and 4.',
    parentPrompt: 'Deal one-for-you, one-for-me until the counters are gone.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'every-leftover-stickers',
    unitId: 6,
    skill: 'leftovers',
    title: 'Stickers left over',
    stem: '7 stickers are shared between 2 children, 3 each. How many stickers are left over?',
    stimulus: { type: 'sharing', total: 7, people: 2 },
    accepted: ['1', 'one'],
    explanation: '2 groups of 3 use 6 stickers. 7 − 6 = 1, so one sticker is left over.',
    parentPrompt: 'Do not force the leftover to be torn in half. Leftovers are allowed.',
    difficulty: 'stretch',
  }),
  count({
    slug: 'every-money-two-dollar',
    unitId: 6,
    skill: 'money-count',
    title: 'Coins in the purse',
    stem: 'The purse has two $1 coins and one $2 coin. How many dollars is that?',
    stimulus: { type: 'coins', coins: [{ value: 1, count: 2 }, { value: 2, count: 1 }] },
    accepted: ['4', 'four'],
    explanation: '$1 + $1 + $2 = $4. Count the value, not the number of coins (there are 3 coins).',
    parentPrompt: 'If they say 3, they counted coins. If they say 12, they read the digits in a line.',
    difficulty: 'core',
  }),
  choice({
    slug: 'every-coin-five-cents',
    unitId: 6,
    skill: 'money-count',
    title: 'Name the 5c coin',
    stem: 'This copper coin has 5c on it. Which coin is it?',
    stimulus: { type: 'coins', coins: [{ value: 5, count: 1, unit: 'cent' }] },
    options: ['5c', '10c', '$1', '$2'],
    correctIndex: 0,
    explanation: 'The copper coin with 5c written on it is 5 cents.',
    parentPrompt: 'Compare a real 5c and 10c if you have them. Do not add shop change yet.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-coin-ten-cents',
    unitId: 6,
    skill: 'money-count',
    title: 'Name the 10c coin',
    stem: 'This silver coin has 10c on it. Which coin is it?',
    stimulus: { type: 'coins', coins: [{ value: 10, count: 1, unit: 'cent' }] },
    options: ['10c', '5c', '$1', '$2'],
    correctIndex: 0,
    explanation: 'The silver coin with 10c written on it is 10 cents.',
    parentPrompt: 'Compare a real 10c and 5c if you have them. Do not add shop change yet.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-coin-one-dollar',
    unitId: 6,
    skill: 'money-count',
    title: 'Name the one-dollar coin',
    stem: 'This gold coin has $1 on it. Which coin is it?',
    stimulus: { type: 'coins', coins: [{ value: 1, count: 1, unit: 'dollar' }] },
    options: ['$1', '5c', '10c', '$2'],
    correctIndex: 0,
    explanation: 'The gold coin with $1 is one dollar. $2 is a smaller gold coin.',
    parentPrompt: 'Hold $1 and $2. Talk about the size and the writing, not shopping.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-coin-two-dollars',
    unitId: 6,
    skill: 'money-count',
    title: 'Name the two-dollar coin',
    stem: 'This smaller gold coin has $2 on it. Which coin is it?',
    stimulus: { type: 'coins', coins: [{ value: 2, count: 1, unit: 'dollar' }] },
    options: ['$2', '5c', '10c', '$1'],
    correctIndex: 0,
    explanation: 'The smaller gold coin with $2 is two dollars. $1 is the bigger gold coin.',
    parentPrompt: 'In Australia the $2 coin is smaller than $1. Read the writing, not just the size.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-coin-worth-more',
    unitId: 6,
    skill: 'money-count',
    title: 'Which coin is worth more?',
    stem: 'Look at $2 and 10c. Which coin is worth more?',
    stimulus: {
      type: 'coins',
      coins: [
        { value: 2, count: 1, unit: 'dollar' },
        { value: 10, count: 1, unit: 'cent' },
      ],
    },
    options: ['$2', '10c', 'Same', '10c is bigger'],
    correctIndex: 0,
    explanation: '$2 is worth more than 10c. A smaller-looking coin can still be worth more.',
    parentPrompt: 'If they pick 10c, they went by size. Point to the writing on each coin.',
    difficulty: 'core',
  }),
  count({
    slug: 'every-coin-count-tens',
    unitId: 6,
    skill: 'money-count',
    title: 'Three 10c coins',
    stem: 'Here are three 10c coins. How many coins are there?',
    stimulus: { type: 'coins', coins: [{ value: 10, count: 3, unit: 'cent' }] },
    accepted: ['3', 'three'],
    explanation: 'Count the coins: 1, 2, 3. Do not add the 10s yet.',
    parentPrompt: 'If they say 30, they added the cents. This card only asks how many coins.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-duration-sleep',
    unitId: 6,
    skill: 'duration-compare',
    title: 'Sleep or shoes',
    stem: 'Which takes a longer time: a night of sleep, or putting on shoes?',
    stimulus: {
      type: 'duration',
      left: { icon: 'bed', label: 'Sleep' },
      right: { icon: 'shoe', label: 'Shoes' },
    },
    options: ['Sleep', 'Shoes', 'Same', 'Need a clock'],
    correctIndex: 0,
    explanation: 'A sleep lasts the night. Putting on shoes is quick.',
    parentPrompt: 'Ask for another long time and a short time from their day.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-yesterday-friday',
    unitId: 6,
    skill: 'days-sequence',
    title: 'The day before Friday',
    stem: 'Today is Friday. What day was yesterday?',
    stimulus: { type: 'dayStrip', highlight: 'Fri' },
    options: ['Thursday', 'Saturday', 'Friday', 'Monday'],
    correctIndex: 0,
    explanation: 'Yesterday is the day before. The day before Friday is Thursday.',
    parentPrompt: 'Walk one step left on the day strip.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-month-after-june',
    unitId: 6,
    skill: 'months-sequence',
    title: 'The month after June',
    stem: 'The strip shows June. What month comes next?',
    stimulus: {
      type: 'dayStrip',
      days: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
      highlight: 'Jun',
    },
    options: ['July', 'May', 'June', 'August'],
    correctIndex: 0,
    explanation: 'After June comes July. May is the month before.',
    parentPrompt: 'Say the months up to June, then wait for them to say July.',
    difficulty: 'core',
  }),
  choice({
    slug: 'every-between-friends',
    unitId: 6,
    skill: 'position',
    title: 'Who stands in the middle?',
    stem: 'Mia, Ali, and Sam stand in a line. Who is between Mia and Sam?',
    stimulus: { type: 'playground', scene: 'between' },
    options: ['Ali', 'Mia', 'Sam', 'No one'],
    correctIndex: 0,
    explanation: 'Between means in the middle. Ali stands between Mia and Sam.',
    parentPrompt: 'Make the line with three toys and swap who is in the middle.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-next-to-slide',
    unitId: 6,
    skill: 'position',
    title: 'Next to the slide',
    stem: 'Mia stands next to the slide. Sam is across the playground. Who is next to the slide?',
    stimulus: { type: 'playground', scene: 'next' },
    options: ['Mia', 'Sam', 'The slide', 'Cannot tell'],
    correctIndex: 0,
    explanation: 'Next to means beside. Mia stands beside the slide. Sam is farther away.',
    parentPrompt: 'Stand one toy beside a book and one toy across the room. Ask “next to”.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-in-front-slide',
    unitId: 6,
    skill: 'position',
    title: 'In front of the slide',
    stem: 'Mia is standing in front of the slide. Who is in front?',
    stimulus: { type: 'playground', scene: 'front' },
    options: ['Mia', 'The slide', 'Sam', 'Cannot tell'],
    correctIndex: 0,
    explanation: 'In front means closer to you than the slide. That is Mia.',
    parentPrompt: 'Put a toy in front of a chair and one behind. Ask both words.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-behind-slide',
    unitId: 6,
    skill: 'position',
    title: 'Behind the slide',
    stem: 'Sam is standing behind the slide. Who is behind?',
    stimulus: { type: 'playground', scene: 'behind' },
    options: ['Sam', 'Mia', 'The slide', 'Cannot tell'],
    correctIndex: 0,
    explanation: 'Behind means on the far side of the slide. That is Sam.',
    parentPrompt: 'If they say the slide, they named the landmark, not the child.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-chance-rain',
    unitId: 6,
    skill: 'chance-language',
    title: 'Might it rain?',
    stem: 'Grey clouds are out. It might rain. Which word fits best?',
    stimulus: { type: 'groups', groups: [{ count: 1, icon: 'rain', label: 'Clouds' }] },
    options: ['Might', 'Will', "Won't", 'Need a clock'],
    correctIndex: 0,
    explanation: 'Rain is possible, but not sure. Might is the word.',
    parentPrompt: 'Contrast with the sun coming up (will) and a flying cow (won’t).',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-chance-cow-fly',
    unitId: 6,
    skill: 'chance-language',
    title: 'A cow will not fly',
    stem: 'A cow will not fly to assembly. Which word fits best?',
    stimulus: { type: 'groups', groups: [{ count: 1, icon: 'cow', label: 'A cow' }] },
    options: ["Won't", 'Will', 'Might', 'Need a dice'],
    correctIndex: 0,
    explanation: 'A cow flying to assembly will not happen. Won’t means it will not.',
    parentPrompt: 'Keep it playful. The point is certain / possible / impossible.',
    difficulty: 'kindy',
  }),

  // ───────── Unit 7 · Groups and measure ─────────
  choice({
    slug: 'groups-plates-not-equal',
    unitId: 7,
    skill: 'equal-groups',
    title: 'Which plate is not equal?',
    stem: 'Plate A and plate B have 4 apples. Plate C has 3. Which plate is not equal?',
    stimulus: {
      type: 'groups',
      groups: [
        { count: 4, icon: 'apple', label: 'A' },
        { count: 4, icon: 'apple', label: 'B' },
        { count: 3, icon: 'apple', label: 'C' },
      ],
    },
    options: ['A', 'B', 'C', 'All same'],
    correctIndex: 2,
    explanation: 'Equal groups have the same number. Plate C has 3, so it is not equal.',
    parentPrompt: 'Ask “same number on each plate?” before they tap.',
    difficulty: 'kindy',
  }),
  yesNo({
    slug: 'groups-two-same-plates',
    unitId: 7,
    skill: 'equal-groups',
    title: 'Two plates of four',
    stem: 'Both plates have 4 apples. Are the groups equal?',
    stimulus: {
      type: 'groups',
      groups: [
        { count: 4, icon: 'apple', label: 'Plate A' },
        { count: 4, icon: 'apple', label: 'Plate B' },
      ],
    },
    yes: true,
    explanation: 'Equal means the same number in each group. 4 and 4 are equal.',
    parentPrompt: 'Move one apple and ask again.',
    difficulty: 'kindy',
  }),
  yesNo({
    slug: 'groups-five-and-three',
    unitId: 7,
    skill: 'equal-groups',
    title: 'Five and three plates',
    stem: 'One plate has 5 apples. The other has 3. Are the groups equal?',
    stimulus: {
      type: 'groups',
      groups: [
        { count: 5, icon: 'apple', label: 'Plate A' },
        { count: 3, icon: 'apple', label: 'Plate B' },
      ],
    },
    yes: false,
    explanation: '5 and 3 are not the same, so the groups are not equal.',
    parentPrompt: 'How many more would make them equal? (2 more on the 3 plate.)',
    difficulty: 'kindy',
  }),
  count({
    slug: 'groups-two-of-four',
    unitId: 7,
    skill: 'equal-groups',
    title: 'Two groups of four',
    stem: 'There are 2 plates. Each plate has 4 apples. How many apples altogether?',
    stimulus: {
      type: 'groups',
      groups: [
        { count: 4, icon: 'apple', label: 'Plate 1' },
        { count: 4, icon: 'apple', label: 'Plate 2' },
      ],
    },
    accepted: ['8', 'eight'],
    explanation: '2 groups of 4 is 4 and 4, which is 8.',
    parentPrompt: 'Count one plate, then keep counting the next plate.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'groups-three-of-two',
    unitId: 7,
    skill: 'equal-groups',
    title: 'Three groups of two',
    stem: 'There are 3 plates. Each plate has 2 apples. How many apples altogether?',
    stimulus: {
      type: 'groups',
      groups: [
        { count: 2, icon: 'apple', label: 'Plate 1' },
        { count: 2, icon: 'apple', label: 'Plate 2' },
        { count: 2, icon: 'apple', label: 'Plate 3' },
      ],
    },
    accepted: ['6', 'six'],
    explanation: '3 groups of 2 is 2, then 4, then 6. Not times tables yet — just count the groups.',
    parentPrompt: 'Skip count 2, 4, 6 if they are ready. Otherwise count each apple.',
    difficulty: 'core',
  }),
  yesNo({
    slug: 'halves-ribbon-middle',
    unitId: 7,
    skill: 'halves',
    title: 'A mark in the middle',
    stem: 'The mark sits in the middle of the ribbon. Is that halfway?',
    stimulus: { type: 'halves', kind: 'ribbon', mark: 'mid' },
    yes: true,
    explanation: 'Halfway is the middle. Both sides of the mark are the same length.',
    parentPrompt: 'Fold a paper ribbon. The fold is halfway.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'halves-sandwich-equal',
    unitId: 7,
    skill: 'halves',
    title: 'Which sandwich is a half?',
    stem: 'Sandwich A is cut into two equal pieces. Sandwich B is cut into a small piece and a big piece. Which is cut in half?',
    stimulus: { type: 'halves', kind: 'sandwich', equal: true },
    options: ['A', 'B', 'Both', 'Neither'],
    correctIndex: 0,
    explanation: 'Half means two pieces the same size. That is sandwich A.',
    parentPrompt: 'If they pick B, they saw “cut into two” but the pieces are not equal.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'halves-eight-apples',
    unitId: 7,
    skill: 'halves',
    title: 'Half of the apples for Sam',
    stem: 'There are 8 apples. Half are for Sam. How many apples does Sam get?',
    stimulus: { type: 'halves', kind: 'group', total: 8 },
    accepted: ['4', 'four'],
    explanation: 'Half of 8 is 4. Two equal groups of 4 make 8.',
    parentPrompt: 'Share into two equal piles. Year 1 can say “half of 8 is 4”.',
    difficulty: 'core',
  }),
  count({
    slug: 'measure-pencil-blocks',
    unitId: 7,
    skill: 'informal-length',
    title: 'How long is the pencil?',
    stem: 'The pencil sits next to the blocks. How many blocks long is the pencil?',
    stimulus: { type: 'measureUnits', kind: 'length', units: 6, item: 'pencil' },
    accepted: ['6', 'six'],
    explanation: 'Line the blocks up with the pencil. It is 6 blocks long.',
    parentPrompt: 'No gaps and no overlaps. That is the rule for informal units.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'measure-shoe-blocks',
    unitId: 7,
    skill: 'informal-length',
    title: 'How long is the shoe?',
    stem: 'The shoe sits next to the blocks. How many blocks long is the shoe?',
    stimulus: { type: 'measureUnits', kind: 'length', units: 4, item: 'shoe' },
    accepted: ['4', 'four'],
    explanation: 'The shoe is 4 blocks long. Count the blocks, not the shoe.',
    parentPrompt: 'Start at one end. If they skip a block, start again.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'measure-apple-cubes',
    unitId: 7,
    skill: 'informal-mass',
    title: 'Cubes to balance the apple',
    stem: 'The apple balances 5 cubes. How many cubes match the apple?',
    stimulus: { type: 'measureUnits', kind: 'mass', units: 5, item: 'apple' },
    accepted: ['5', 'five'],
    explanation: 'The two sides match. The apple has the same mass as 5 cubes.',
    parentPrompt: 'Keep the cubes the same size. Mixing big and small cubes breaks the measure.',
    difficulty: 'core',
  }),
  count({
    slug: 'measure-jug-cups',
    unitId: 7,
    skill: 'informal-capacity',
    title: 'Cups that fill the jug',
    stem: 'It took these cups to fill the jug. How many cups fill the jug?',
    stimulus: { type: 'measureUnits', kind: 'capacity', units: 3, item: 'bowl' },
    accepted: ['3', 'three'],
    explanation: 'Count the cups: 3 cups fill the jug.',
    parentPrompt: 'Use the same cup each time. A bigger cup would need fewer pours.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'see-match-four-shells',
    unitId: 1,
    skill: 'subitise-perceptual',
    title: 'Find the four shells',
    stem: 'Look at the big number, then tap the tray that shows that many shells.',
    stimulus: {
      type: 'matchNumber',
      target: 4,
      choices: [
        { count: 2, icon: 'shell' },
        { count: 4, icon: 'shell' },
        { count: 6, icon: 'shell' },
      ],
    },
    options: ['2 shells', '4 shells', '6 shells'],
    correctIndex: 1,
    explanation: 'The number is 4. Only the middle tray has four shells.',
    parentPrompt: 'Cover the number, ask them to find 4, then uncover it to check.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'see-match-five-buttons',
    unitId: 1,
    skill: 'subitise-structured',
    title: 'Find the five buttons',
    stem: 'The number is 5. Tap the tray that has five buttons.',
    stimulus: {
      type: 'matchNumber',
      target: 5,
      choices: [
        { count: 5, icon: 'button' },
        { count: 3, icon: 'button' },
        { count: 4, icon: 'button' },
      ],
    },
    options: ['5 buttons', '3 buttons', '4 buttons'],
    correctIndex: 0,
    explanation: 'A five-pattern is a full handful of buttons. The other trays are 3 and 4.',
    parentPrompt: 'Ask “Do you need to count, or can you see the five?”',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'see-odd-star-among-leaves',
    unitId: 1,
    skill: 'compare-collections',
    title: 'The star that does not belong',
    stem: 'Three pictures are the same kind of thing. Tap the one that is not like the others.',
    stimulus: {
      type: 'oddOneOut',
      items: [
        { icon: 'leaf' },
        { icon: 'leaf' },
        { icon: 'star' },
        { icon: 'leaf' },
      ],
    },
    options: ['First leaf', 'Second leaf', 'The star', 'Last leaf'],
    correctIndex: 2,
    explanation: 'Three are leaves. The star is the one that does not belong.',
    parentPrompt: 'Ask “same or different?” before they tap. Do not name the star for them.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'count-more-garden-leaves',
    unitId: 2,
    skill: 'compare-collections',
    title: 'More leaves on the path',
    stem: 'The top path has more leaves. How many more leaves are on the top path than the bottom path?',
    stimulus: {
      type: 'howManyMore',
      left: { count: 8, label: 'Top path', icon: 'leaf' },
      right: { count: 5, label: 'Bottom path', icon: 'leaf' },
    },
    accepted: ['3', 'three'],
    explanation: 'Match 5 to 5. Three leaves stick out. How many more is 3, not 8.',
    parentPrompt: 'Line them up. The leftover row is the answer, not the longer total.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'count-more-lunch-pears',
    unitId: 2,
    skill: 'compare-difference',
    title: 'Pears left in the bowl',
    stem: 'Sam’s bowl has more pears. How many more pears does Sam have than Mia?',
    stimulus: {
      type: 'howManyMore',
      left: { count: 6, label: 'Sam', icon: 'pear' },
      right: { count: 4, label: 'Mia', icon: 'pear' },
    },
    accepted: ['2', 'two'],
    explanation: '6 and 4. Match 4 to 4. Two pears are extra, so Sam has 2 more.',
    parentPrompt: 'If they say 6, they named Sam’s total. Ask “more than Mia” again.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'count-odd-shell-tray',
    unitId: 2,
    skill: 'cardinality',
    title: 'The tray that does not match',
    stem: 'Three trays have the same number of shells. Tap the tray that has a different number.',
    stimulus: {
      type: 'oddOneOut',
      items: [
        { icon: 'shell', count: 2 },
        { icon: 'shell', count: 2 },
        { icon: 'shell', count: 3 },
        { icon: 'shell', count: 2 },
      ],
    },
    options: ['2 shells', 'Another 2', '3 shells', 'Last 2'],
    correctIndex: 2,
    explanation: 'Three trays show 2. The third tray shows 3, so that is the different one.',
    parentPrompt: 'They should compare how many, not how the shells are placed.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'parts-more-red-beads',
    unitId: 3,
    skill: 'five-wise',
    title: 'Beads past a full five',
    stem: 'The red row is a five. How many more beads does the gold row have than the red row?',
    stimulus: {
      type: 'howManyMore',
      left: { count: 8, label: 'Gold row', icon: 'bead', color: 'gold' },
      right: { count: 5, label: 'Red row', icon: 'bead', color: 'red' },
    },
    accepted: ['3', 'three'],
    explanation: '5 and 8. Five is a landmark. 8 is 5 and 3 more.',
    parentPrompt: 'Point to the extra three after the five. Do not recount from one.',
    difficulty: 'kindy',
  }),
  count({
    slug: 'story-more-apples-basket',
    unitId: 4,
    skill: 'compare-difference',
    title: 'Apples still on the bench',
    stem: 'The bench has more apples than the basket. How many more apples are on the bench?',
    stimulus: {
      type: 'howManyMore',
      left: { count: 9, label: 'Bench', icon: 'apple' },
      right: { count: 6, label: 'Basket', icon: 'apple' },
    },
    accepted: ['3', 'three'],
    explanation: 'Compare stories ask for the difference. Match 6 to 6. Three apples stick out.',
    parentPrompt: 'If they say 15 they added. If they say 9 they named the bench only.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-odd-bowl-and-star',
    unitId: 6,
    skill: 'shape-2d',
    title: 'Bowls and a star',
    stem: 'Tap the picture that is not a bowl.',
    stimulus: {
      type: 'oddOneOut',
      items: [
        { icon: 'bowl', color: '#4A86B8' },
        { icon: 'bowl', color: '#4A7A64' },
        { icon: 'bowl', color: '#C49B7A' },
        { icon: 'star', color: '#E8B84A' },
      ],
    },
    options: ['Blue bowl', 'Green bowl', 'Brown bowl', 'The star'],
    correctIndex: 3,
    explanation: 'The first three are bowls. The star is a different kind of thing.',
    parentPrompt: 'Colour is a trick. Ask “what kind of thing is this?” not “what colour?”',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'every-odd-triangle-in-circles',
    unitId: 6,
    skill: 'shape-2d',
    title: 'A triangle in the circles',
    stem: 'Three shapes are circles. Tap the shape that is not a circle.',
    stimulus: {
      type: 'oddOneOut',
      items: [
        { icon: 'circle', color: '#E15A4A' },
        { icon: 'circle', color: '#E8B84A' },
        { icon: 'triangle', color: '#4A86B8' },
        { icon: 'circle', color: '#3E8B6A' },
      ],
    },
    options: ['Red circle', 'Gold circle', 'The triangle', 'Green circle'],
    correctIndex: 2,
    explanation: 'Circles are round. The blue shape has three sides, so it is the triangle.',
    parentPrompt: 'Let them run a finger around each edge before they tap.',
    difficulty: 'kindy',
  }),
  choice({
    slug: 'see-match-three-apples',
    unitId: 1,
    skill: 'cardinality',
    title: 'Match three apples',
    stem: 'Find the tray that matches the number 3.',
    stimulus: {
      type: 'matchNumber',
      target: 3,
      choices: [
        { count: 5, icon: 'apple' },
        { count: 1, icon: 'apple' },
        { count: 3, icon: 'apple' },
      ],
    },
    options: ['5 apples', '1 apple', '3 apples'],
    correctIndex: 2,
    explanation: 'The number is 3. The last tray has three apples, not five or one.',
    parentPrompt: 'If they tap five, they chose the fullest tray. Point back to the 3.',
    difficulty: 'kindy',
  }),
];

function withSortOrder(drafts: Draft[]): EarlyMathItem[] {
  const counters = new Map<number, number>();
  return drafts.map((draft) => {
    const sortOrder = (counters.get(draft.unitId) ?? 0) + 1;
    counters.set(draft.unitId, sortOrder);
    if (!EARLY_MATH_UNITS.some((unit) => unit.id === draft.unitId)) {
      throw new Error(`Unknown maths unit ${draft.unitId}`);
    }
    return {
      slug: draft.slug,
      unitId: draft.unitId,
      skill: draft.skill,
      kind: draft.kind ?? 'choice',
      title: draft.title,
      stem: draft.stem,
      stimulus: draft.stimulus,
      options: draft.options,
      correctIndex: draft.correctIndex,
      accepted: draft.accepted,
      explanation: draft.explanation,
      parentPrompt: draft.parentPrompt,
      difficulty: draft.difficulty ?? 'core',
      sortOrder,
    };
  });
}

export const SEED_EARLY_MATH: EarlyMathItem[] = withSortOrder(DRAFTS);
