import type {
  MiniItemKind,
  OrderPrompt,
  RewritePrompt,
  ShortWritePrompt,
  SpellingPrompt,
} from '@/lib/mini-item-kinds';
import type { MiniSkill } from '@/lib/seed-mini-drills';
import type { WritingType } from '@/lib/units';

export type SeedMixedMiniDrill = {
  slug: string;
  module_id: number;
  prompt_type: WritingType;
  skill: MiniSkill;
  item_kind: Exclude<MiniItemKind, 'choice'>;
  title: string;
  stem: string;
  explanation: string;
  sort_order: number;
  prompt: SpellingPrompt | RewritePrompt | OrderPrompt | ShortWritePrompt;
};

function mixed(
  module_id: number,
  prompt_type: WritingType,
  skill: MiniSkill,
  item_kind: SeedMixedMiniDrill['item_kind'],
  sort_order: number,
  title: string,
  stem: string,
  explanation: string,
  prompt: SeedMixedMiniDrill['prompt'],
): SeedMixedMiniDrill {
  return {
    slug: `unit-${module_id}-${item_kind}-${sort_order}`,
    module_id,
    prompt_type,
    skill,
    item_kind,
    title,
    stem,
    explanation,
    sort_order,
    prompt,
  };
}

function spelling(
  module_id: number,
  prompt_type: WritingType,
  sort_order: number,
  title: string,
  stem: string,
  sentence: string,
  misspelled: string,
  accepted: string[],
  explanation: string,
): SeedMixedMiniDrill {
  return mixed(
    module_id,
    prompt_type,
    'vocabulary',
    'spelling',
    sort_order,
    title,
    stem,
    explanation,
    { sentence, misspelled, accepted },
  );
}

function rewrite(
  module_id: number,
  prompt_type: WritingType,
  skill: MiniSkill,
  sort_order: number,
  title: string,
  stem: string,
  prompt: Omit<RewritePrompt, 'requireCapital' | 'requireEndPunct'> & {
    requireCapital?: boolean;
    requireEndPunct?: boolean;
  },
  explanation: string,
): SeedMixedMiniDrill {
  return mixed(module_id, prompt_type, skill, 'rewrite', sort_order, title, stem, explanation, {
    requireCapital: true,
    requireEndPunct: true,
    ...prompt,
  });
}

function order(
  module_id: number,
  prompt_type: WritingType,
  skill: MiniSkill,
  sort_order: number,
  title: string,
  stem: string,
  sentences: string[],
  shuffle: number[],
  explanation: string,
): SeedMixedMiniDrill {
  return mixed(module_id, prompt_type, skill, 'order', sort_order, title, stem, explanation, {
    sentences,
    shuffled: shuffle.map((index) => sentences[index] ?? ''),
  });
}

function shortWrite(
  module_id: number,
  prompt_type: WritingType,
  skill: MiniSkill,
  sort_order: number,
  title: string,
  stem: string,
  prompt: ShortWritePrompt,
  explanation: string,
): SeedMixedMiniDrill {
  return mixed(
    module_id,
    prompt_type,
    skill,
    'short_write',
    sort_order,
    title,
    stem,
    explanation,
    {
      requireCapital: true,
      requireEndPunct: true,
      ...prompt,
    },
  );
}

/**
 * Always-visible mixed mini practice: spelling, rewrite, sentence order,
 * and a 1–2 sentence write. Eight per unit, after the ten multiple-choice
 * starters. Marked locally against a short checklist.
 */
export const SEED_MIXED_MINI_DRILLS: SeedMixedMiniDrill[] = [
  // ── Unit 1 Narrative ──
  spelling(
    1,
    'narrative',
    11,
    'Find the spelling',
    'One word in this story sentence is spelled wrongly. Type the correct spelling.',
    'The gardian opened the rusty library gate.',
    'gardian',
    ['guardian'],
    'guardian is the person who looks after something. Double-check the middle vowels: guard-i-an.',
  ),
  spelling(
    1,
    'narrative',
    12,
    'i before e',
    'Find the spelling mistake and type the word correctly.',
    'Maya recieved the brass key from Leah.',
    'recieved',
    ['received'],
    'received follows “i before e, except after c”.',
  ),
  rewrite(
    1,
    'narrative',
    'format',
    13,
    'Make it a story line',
    'This line belongs in a letter. Rewrite it as one story sentence.',
    {
      original: 'Dear Principal, I wish to complain about the dark library.',
      hint: 'Start in the moment. Do not use a letter greeting or sign-off.',
      mustInclude: ['library'],
      mustNotInclude: ['Dear', 'sincerely', 'Principal'],
      minWords: 8,
      sample: 'Maya stepped into the dark library and the door clicked shut.',
    },
    'A narrative follows a character in a place. Letter parts such as Dear and Principal belong in another unit.',
  ),
  rewrite(
    1,
    'narrative',
    'punctuation',
    14,
    'Add the speech marks',
    'Rewrite this so the spoken words are punctuated correctly.',
    {
      original: 'help whispered Maya',
      hint: 'Capital letter, speech marks, and an end mark inside the quote.',
      mustInclude: ['Help', 'Maya'],
      minWords: 3,
      requireQuote: true,
      sample: '“Help!” Maya whispered.',
    },
    'Put the spoken words inside speech marks and keep the punctuation with those words.',
  ),
  order(
    1,
    'narrative',
    'structure',
    15,
    'Story order',
    'Put these story sentences in an order a marker can follow.',
    [
      'Maya stopped at the rusty library gate.',
      'She pushed it open and the garden was silent.',
      'Something pale moved behind the fountain.',
      'She stepped back and let the gate clang shut.',
    ],
    [2, 0, 3, 1],
    'Start in the place, build the problem, then finish the moment. Markers reward a beginning, a change, and an ending.',
  ),
  order(
    1,
    'narrative',
    'format',
    16,
    'Keep it a story',
    'Put these story sentences in the order they happen.',
    [
      'Leah checked the dark shelves before the bell.',
      'The brass key was not on the hook.',
      'She searched the reading nook twice.',
      'She slipped the spare key into her pocket and ran.',
    ],
    [2, 0, 3, 1],
    'A story stays with one character and one problem. Keep events in the order they happen.',
  ),
  shortWrite(
    1,
    'narrative',
    'structure',
    17,
    'Open in the moment',
    'Write two sentences that start a story at a locked door. Do not tell us “this is a story”.',
    {
      task: 'Open a narrative at a locked door. Show the place and a small problem.',
      mustInclude: ['door'],
      mustNotInclude: ['Dear', 'headline'],
      minWords: 12,
      maxWords: 50,
      sample: 'The locked door would not turn. Sam pressed his ear to the wood and waited.',
    },
    'Start in the moment. Name the door and let the reader see a problem begin.',
  ),
  shortWrite(
    1,
    'narrative',
    'audience',
    18,
    'Let them see the cellar',
    'A reader has never been in this cellar. Write one or two sentences that help them see it.',
    {
      task: 'Describe the cellar for a reader who was not there.',
      mustInclude: ['cellar'],
      mustNotInclude: ['lol', 'ngl'],
      minWords: 10,
      maxWords: 45,
      sample: 'The cellar air tasted of wet stone, and the steps vanished after the third tread.',
    },
    'Show a concrete detail. Slang and “you know what it’s like” leave the marker out.',
  ),

  // ── Unit 2 Diary ──
  spelling(
    2,
    'diary_entry',
    11,
    'Find the spelling',
    'One word is spelled wrongly. Type the correct spelling.',
    'I was embarassed after I left my lunchbox on the bench.',
    'embarassed',
    ['embarrassed'],
    'embarrassed has two r’s and two s’s: em-barr-assed.',
  ),
  spelling(
    2,
    'diary_entry',
    12,
    'A tricky adverb',
    'Find the spelling mistake and type the word correctly.',
    'I definately hid it under the bag hooks.',
    'definately',
    ['definitely'],
    'definitely comes from definite. Keep the i in the middle: defin-ite-ly.',
  ),
  rewrite(
    2,
    'diary_entry',
    'format',
    13,
    'Make it first person',
    'This line sounds like news. Rewrite it as a diary sentence.',
    {
      original: 'A Year 5 student lost a lunchbox after sport.',
      hint: 'Use I. Keep it personal, not a report.',
      mustInclude: ['I', 'lunchbox'],
      mustNotInclude: ['student', 'BREAKING'],
      minWords: 7,
      sample: 'I lost my lunchbox after sport and the bench was empty.',
    },
    'Diary is first person. News reports name “a student” and keep the writer out.',
  ),
  rewrite(
    2,
    'diary_entry',
    'punctuation',
    14,
    'Fix I’m',
    'Rewrite this diary line with the missing apostrophe and a full stop.',
    {
      original: 'im still hungry after fruit',
      hint: 'I’m = I am. Start with a capital and end the sentence.',
      mustInclude: ["I'm"],
      minWords: 5,
      sample: "I'm still hungry after fruit.",
    },
    'I’m needs the apostrophe. A capital and one full stop is enough.',
  ),
  order(
    2,
    'diary_entry',
    'structure',
    15,
    'Diary order',
    'Put these diary lines in a clear order: when, what happened, how it felt, a thought for later.',
    [
      'Tuesday 3 March.',
      'I left my lunchbox on the oval bench.',
      'I still feel silly about it.',
      'Tomorrow I will check the lost-property box.',
    ],
    [2, 0, 3, 1],
    'A marker can follow a diary that names the day, tells the event, shows a feeling, then looks ahead.',
  ),
  order(
    2,
    'diary_entry',
    'format',
    16,
    'Stay in the day',
    'Put these personal lines in time order.',
    [
      'Dear Diary, sport went wrong from the start.',
      'Coach asked who had left a lunchbox on the bench.',
      'My face went hot when I saw the empty peg.',
      'I owned up and Coach was kind.',
    ],
    [1, 0, 3, 2],
    'Keep one day and one voice. Event, then feeling, then what you did.',
  ),
  shortWrite(
    2,
    'diary_entry',
    'structure',
    17,
    'Event and feeling',
    'Write two diary sentences: what happened, then how you felt.',
    {
      task: 'Write about losing a lunchbox after sport. Use I.',
      mustInclude: ['I', 'lunchbox'],
      mustNotInclude: ['Yours', 'headline'],
      minWords: 12,
      maxWords: 50,
      sample: 'I left my lunchbox on the bench after sport. I still feel silly about walking home without it.',
    },
    'Diary needs the event and the feeling. Letter endings and headlines belong elsewhere.',
  ),
  shortWrite(
    2,
    'diary_entry',
    'audience',
    18,
    'A last thought',
    'Write one honest closing sentence for this diary, as if you are writing to yourself.',
    {
      task: 'Close the lunchbox diary with a thought about tomorrow or what you learned.',
      mustInclude: ['I'],
      mustNotInclude: ['sincerely', 'Ladies'],
      minWords: 8,
      maxWords: 35,
      sample: 'Tomorrow I will check the bench before I leave the oval.',
    },
    'A last thought finishes the day. Speeches and letter sign-offs miss the diary audience.',
  ),

  // ── Unit 3 News report ──
  spelling(
    3,
    'news_report',
    11,
    'School leader',
    'Find the spelling mistake and type the word correctly.',
    'The princapal closed the oval after overnight rain.',
    'princapal',
    ['principal'],
    'principal is the school leader. principle is a rule. News reports need the school spelling.',
  ),
  spelling(
    3,
    'news_report',
    12,
    'The sports ground',
    'Find the spelling mistake and type the word correctly.',
    'Staff said the feild was unsafe for play.',
    'feild',
    ['field'],
    'field is i before e here: f-ie-ld.',
  ),
  rewrite(
    3,
    'news_report',
    'format',
    13,
    'Facts, not feelings',
    'This line belongs in a diary. Rewrite it as one calm news sentence.',
    {
      original: 'I felt so sad about the mud on the oval.',
      hint: 'Who, what, where. No I felt.',
      mustInclude: ['oval'],
      mustNotInclude: ['I', 'sad'],
      minWords: 8,
      sample: 'The oval closed at 9am after overnight rain, staff said.',
    },
    'News is facts in a calm voice. Diary feelings belong in another unit.',
  ),
  rewrite(
    3,
    'news_report',
    'punctuation',
    14,
    'Quote the speaker',
    'Rewrite this so the exact words sit inside speech marks.',
    {
      original: 'Safety comes first said Ms Chen',
      hint: 'Add speech marks and a comma before the speaker.',
      mustInclude: ['Safety', 'Chen'],
      minWords: 6,
      requireQuote: true,
      sample: '“Safety comes first,” Ms Chen said.',
    },
    'Put the exact words in speech marks and close them before the speaker tag.',
  ),
  order(
    3,
    'news_report',
    'structure',
    15,
    'Facts first',
    'Put these report sentences in news order: main facts, extra fact, quote, what happens next.',
    [
      'Westmead Public School closed its oval at 9am after overnight rain.',
      'Staff measured 40 millimetres of rain on the cricket pitch.',
      '“Safety comes first,” Ms Chen said.',
      'Sport will be held in the hall until Friday.',
    ],
    [2, 0, 3, 1],
    'News is not a mystery story. Who, what, where, and when come first, then a quote and the next step.',
  ),
  order(
    3,
    'news_report',
    'format',
    16,
    'Keep it a report',
    'Put these factual lines in a clear report order.',
    [
      'Play was moved to the hall after the oval flooded.',
      'Puddles covered the cricket pitch this morning.',
      'A Year 6 student said the water reached her socks.',
      'The oval may reopen on Friday if it dries.',
    ],
    [1, 0, 3, 2],
    'Lead with the event, add a detail, add a voice, then the next step.',
  ),
  shortWrite(
    3,
    'news_report',
    'structure',
    17,
    'Who, what, where',
    'Write one opening sentence that tells who, what, where, and when.',
    {
      task: 'Open a news report about a flooded school oval.',
      mustInclude: ['oval'],
      mustNotInclude: ['Dear', 'Diary'],
      minWords: 10,
      maxWords: 40,
      sample: 'Westmead Public School closed its oval at 9am on Tuesday after overnight rain.',
    },
    'Put the main facts near the top. Diary greetings do not belong in a report.',
  ),
  shortWrite(
    3,
    'news_report',
    'audience',
    18,
    'Calm next step',
    'Write one calm sentence for readers who were not at the school.',
    {
      task: 'Tell readers when the oval might reopen. Stay calm. No slang.',
      mustInclude: ['Friday'],
      mustNotInclude: ['lol', 'worst'],
      minWords: 8,
      maxWords: 35,
      sample: 'Staff hope the oval will reopen on Friday if the ground dries.',
    },
    'Readers want a clear next fact. Rants and slang miss the news audience.',
  ),

  // ── Unit 4 Explanation ──
  spelling(
    4,
    'explanation',
    11,
    'Find the spelling',
    'One word is spelled wrongly. Type the correct spelling.',
    'Keep wet and dry scraps in seperate buckets.',
    'seperate',
    ['separate'],
    'separate has an a in the middle: sep-a-rate. A useful memory is “there is a rat in separate”.',
  ),
  spelling(
    4,
    'explanation',
    12,
    'A needed word',
    'Find the spelling mistake and type the word correctly.',
    'Air is neccessary so the scraps can break down.',
    'neccessary',
    ['necessary'],
    'necessary has one c and two s’s: ne-cess-ary.',
  ),
  rewrite(
    4,
    'explanation',
    'format',
    13,
    'How, not a scare',
    'This line belongs in a story. Rewrite it as one explanation sentence.',
    {
      original: 'Maya was very very scared of the worms in the bin.',
      hint: 'Explain how or why. Leave the scare out.',
      mustInclude: ['worms'],
      mustNotInclude: ['scared', 'Maya'],
      minWords: 8,
      sample: 'Worms and air help scraps break down into soil.',
    },
    'Explanation shows how or why. A character’s fear belongs in a narrative.',
  ),
  rewrite(
    4,
    'explanation',
    'punctuation',
    14,
    'End the step',
    'Rewrite this step as a complete sentence.',
    {
      original: 'first add dry leaves then wait',
      hint: 'Capital, then a joining word or a comma, and a full stop.',
      mustInclude: ['leaves'],
      minWords: 6,
      sample: 'First, add dry leaves, then wait.',
    },
    'Steps still need a capital and an end mark so the reader can follow them.',
  ),
  order(
    4,
    'explanation',
    'structure',
    15,
    'Step order',
    'Put these compost steps in the order they happen.',
    [
      'Collect fruit scraps in a dry bucket.',
      'Add dry leaves so air can move through the pile.',
      'Worms and microbes break the scraps down.',
      'Dark soil is left at the bottom of the bin.',
    ],
    [2, 0, 3, 1],
    'Explanations work in a sequence: start, what you add, what happens, the result.',
  ),
  order(
    4,
    'explanation',
    'format',
    16,
    'Cause then effect',
    'Put these how-and-why sentences in a clear order.',
    [
      'Food scraps need air and a little moisture.',
      'If the pile stays wet and closed, it starts to smell.',
      'Turning the pile lets fresh air in.',
      'That is why gardeners mix dry leaves with wet scraps.',
    ],
    [1, 0, 3, 2],
    'Give the rule, the problem, the fix, then the why. That is explanation structure.',
  ),
  shortWrite(
    4,
    'explanation',
    'structure',
    17,
    'Explain one step',
    'Write two sentences that explain one compost step and why it matters.',
    {
      task: 'Explain why dry leaves are added to a compost bin.',
      mustInclude: ['leaves'],
      mustNotInclude: ['BUY', 'Dear'],
      minWords: 12,
      maxWords: 50,
      sample: 'Dry leaves let air move through the scraps. Without air, the pile stays wet and starts to smell.',
    },
    'Name the step and the reason. Ads and letters are other jobs.',
  ),
  shortWrite(
    4,
    'explanation',
    'vocabulary',
    18,
    'Because',
    'Write one because sentence that explains why worms help compost.',
    {
      task: 'Use because to explain why worms help scraps break down.',
      mustInclude: ['because', 'worms'],
      mustNotInclude: ['thingy', 'stuff'],
      minWords: 8,
      maxWords: 35,
      sample: 'Worms help because they mix air into the scraps as they move.',
    },
    'because makes the reason clear. Vague fillers such as stuff lose word-choice marks.',
  ),

  // ── Unit 5 Advice sheet ──
  spelling(
    5,
    'advice_sheet',
    11,
    'Find the spelling',
    'One word is spelled wrongly. Type the correct spelling.',
    'We reccomend you pack a hat for the excursion.',
    'reccomend',
    ['recommend'],
    'recommend has one c and two m’s: re-commend.',
  ),
  spelling(
    5,
    'advice_sheet',
    12,
    'A handy word',
    'Find the spelling mistake and type the word correctly.',
    'A written list is usefull before you leave home.',
    'usefull',
    ['useful'],
    'useful has one l: use-ful.',
  ),
  rewrite(
    5,
    'advice_sheet',
    'format',
    13,
    'Make it advice',
    'This line is a story. Rewrite it as one clear tip.',
    {
      original: 'Tom ran back because he had forgotten his hat again.',
      hint: 'Tell the reader what to do. You or a clear verb works well.',
      mustInclude: ['hat'],
      mustNotInclude: ['Tom'],
      minWords: 6,
      sample: 'Pack a hat the night before the excursion.',
    },
    'Advice tells the reader what to do. A named character running home is a story.',
  ),
  rewrite(
    5,
    'advice_sheet',
    'audience',
    14,
    'Friendly, not slang',
    'Rewrite this tip so a Year 5 class can follow it.',
    {
      original: 'yo dont forget ur bottle ngl',
      hint: 'Clear words. No chat slang.',
      mustInclude: ['bottle'],
      mustNotInclude: ['yo', 'ngl', 'ur'],
      minWords: 6,
      sample: 'Bring a water bottle so you can drink at each stop.',
    },
    'Advice should be friendly and easy to follow. Chat slang leaves some readers out.',
  ),
  order(
    5,
    'advice_sheet',
    'structure',
    15,
    'Tip order',
    'Put these advice lines in a useful order: heading job, first tip, reason, warning.',
    [
      'How to get ready for the excursion.',
      'Pack your hat and bottle the night before.',
      'You will not have time to go back to the classroom.',
      'Do not bring extra money for the gift shop.',
    ],
    [2, 0, 3, 1],
    'A sheet works when the job is clear, then a tip, a reason, and a short warning.',
  ),
  order(
    5,
    'advice_sheet',
    'format',
    16,
    'Do this, then this',
    'Put these getting-ready tips in the order a student should follow.',
    [
      'Check the note for the meeting time.',
      'Lay out your hat, bottle, and lunch.',
      'Put your name on your bag.',
      'Be at the gate five minutes early.',
    ],
    [1, 0, 3, 2],
    'Advice is easier when the steps follow the morning: check, pack, label, arrive.',
  ),
  shortWrite(
    5,
    'advice_sheet',
    'structure',
    17,
    'One clear tip',
    'Write two sentences: a tip, then why it helps.',
    {
      task: 'Give one piece of advice about packing for an excursion.',
      mustInclude: ['pack'],
      mustNotInclude: ['BUY', 'Dear'],
      minWords: 12,
      maxWords: 45,
      sample: 'Pack your hat the night before. That way you will not forget it in the morning rush.',
    },
    'A tip plus a reason is easy for the reader to use. Ads and letters are other forms.',
  ),
  shortWrite(
    5,
    'advice_sheet',
    'audience',
    18,
    'A kind warning',
    'Write one warning sentence that still sounds helpful, not angry.',
    {
      task: 'Warn students not to bring extra money, without shouting.',
      mustInclude: ['money'],
      mustNotInclude: ['stupid', 'worst'],
      minWords: 8,
      maxWords: 35,
      sample: 'Leave extra money at home so it cannot be lost on the bus.',
    },
    'Advice can warn and still stay kind. Insults miss the audience.',
  ),

  // ── Unit 6 Review ──
  spelling(
    6,
    'review',
    11,
    'Find the spelling',
    'One word is spelled wrongly. Type the correct spelling.',
    'The begining of the book is slower than the ending.',
    'begining',
    ['beginning'],
    'beginning keeps the n from begin and adds -ning: begin-ning.',
  ),
  spelling(
    6,
    'review',
    12,
    'A review word',
    'Find the spelling mistake and type the word correctly.',
    'The last chapter may dissappoint readers who wanted a twist.',
    'dissappoint',
    ['disappoint'],
    'disappoint has one s and two p’s: dis-appoint.',
  ),
  rewrite(
    6,
    'review',
    'format',
    13,
    'Judge, then reason',
    'This line is only a feeling. Rewrite it as a review sentence with a reason.',
    {
      original: 'I loved it so much it was amazing.',
      hint: 'Name the book or film and say why. Avoid empty praise.',
      mustInclude: ['because'],
      mustNotInclude: ['amazing'],
      minWords: 8,
      sample: 'I would recommend this book because the last chapter finally explains the map.',
    },
    'A review needs a judgement and a reason. Empty words such as amazing do little work.',
  ),
  rewrite(
    6,
    'review',
    'punctuation',
    14,
    'Title and sentence',
    'Rewrite this as a complete review sentence. Keep the title clear.',
    {
      original: 'the hidden gate is a good book for year 5',
      hint: 'Capital letters and a full stop. You may add because.',
      mustInclude: ['Hidden', 'Gate'],
      minWords: 8,
      sample: 'The Hidden Gate is a good book for Year 5 because the mystery stays clear.',
    },
    'Titles and the start of the sentence take capitals. Finish the thought.',
  ),
  order(
    6,
    'review',
    'structure',
    15,
    'Review shape',
    'Put these review sentences in a useful order: what it is, a strength, a weakness, a recommendation.',
    [
      'The Hidden Gate is a Year 5 mystery set in an old library.',
      'The map puzzle is clever and easy to follow.',
      'The middle chapter repeats the same search twice.',
      'I would still recommend it to readers who like quiet scares.',
    ],
    [2, 0, 3, 1],
    'Tell the reader what you are reviewing, give a plus and a minus, then recommend or not.',
  ),
  order(
    6,
    'review',
    'format',
    16,
    'Stay a review',
    'Put these opinion lines in an order that builds a review.',
    [
      'This film follows two friends who lose a school camera.',
      'The jokes in the first half are sharp.',
      'The ending explains the missing memory card too quickly.',
      'Borrow it if you like school mysteries more than action.',
    ],
    [1, 0, 3, 2],
    'What it is, a strength, a limit, then who should choose it.',
  ),
  shortWrite(
    6,
    'review',
    'structure',
    17,
    'Recommend with because',
    'Write two sentences: your recommendation and one reason.',
    {
      task: 'Recommend The Hidden Gate, or say who should skip it. Use because.',
      mustInclude: ['because'],
      mustNotInclude: ['lol', 'BUY'],
      minWords: 12,
      maxWords: 50,
      sample: 'I would recommend The Hidden Gate to Year 5 readers. I liked it because the map puzzle stays fair.',
    },
    'A recommendation needs a because. Slogans and slang belong in other tasks.',
  ),
  shortWrite(
    6,
    'review',
    'vocabulary',
    18,
    'A precise word',
    'Write one sentence that uses a clearer word than nice or good.',
    {
      task: 'Describe one part of a book or film without using nice or good.',
      mustInclude: ['chapter'],
      mustNotInclude: ['nice', 'good'],
      minWords: 8,
      maxWords: 35,
      sample: 'The last chapter is tense because the map finally matches the cellar door.',
    },
    'Precise everyday words score better than nice and good.',
  ),

  // ── Unit 7 Advertisement ──
  spelling(
    7,
    'advertisement',
    11,
    'Find the spelling',
    'One word is spelled wrongly. Type the correct spelling.',
    'This Saturday’s book fair is a special occassion for families.',
    'occassion',
    ['occasion'],
    'occasion has two c’s and one s: oc-casion.',
  ),
  spelling(
    7,
    'advertisement',
    12,
    'A selling word',
    'Find the spelling mistake and type the word correctly.',
    'Students can by tickets at the office until Friday.',
    'by',
    ['buy'],
    'buy means to pay for something. by is a different word. The sentence needs buy.',
  ),
  rewrite(
    7,
    'advertisement',
    'format',
    13,
    'Sell, don’t report',
    'This line is news. Rewrite it as one advertisement sentence.',
    {
      original: 'The school book fair opens at 9am on Saturday.',
      hint: 'Invite the reader. Name a benefit, not only the time.',
      mustInclude: ['book'],
      mustNotInclude: ['closed', 'flooded'],
      minWords: 8,
      sample: 'Find your next favourite book at Saturday’s school book fair.',
    },
    'An advertisement invites. A news report only states the fact.',
  ),
  rewrite(
    7,
    'advertisement',
    'audience',
    14,
    'School voice, not shout',
    'Rewrite this so a school community would read it.',
    {
      original: 'BUY NOW OR ELSE!!!!',
      hint: 'Name the event and a reason. No all-caps threats.',
      mustInclude: ['fair'],
      mustNotInclude: ['or else'],
      minWords: 7,
      sample: 'Come to the Saturday book fair and take a story home.',
    },
    'School ads can be lively without threats or a row of exclamation marks.',
  ),
  order(
    7,
    'advertisement',
    'structure',
    15,
    'Ad order',
    'Put these advertisement lines in a useful order: hook, what it is, benefit, what to do.',
    [
      'Looking for a story that lasts the holidays?',
      'The school book fair is open Saturday from 9am.',
      'Every purchase helps the library buy new titles.',
      'Bring a bag and meet us in the hall.',
    ],
    [2, 0, 3, 1],
    'Hook the reader, name the event, give a benefit, then tell them what to do.',
  ),
  order(
    7,
    'advertisement',
    'format',
    16,
    'Keep the sell clear',
    'Put these invitation lines in an order that builds an ad.',
    [
      'This Friday lunch, try a free chapter from the new mystery shelf.',
      'Year 5 and 6 can visit the library pop-up.',
      'You will leave with a bookmark and a clue card.',
      'Ask at the desk if you want a turn.',
    ],
    [1, 0, 3, 2],
    'When, who, a treat, then the action. That is enough advertisement structure.',
  ),
  shortWrite(
    7,
    'advertisement',
    'structure',
    17,
    'Write a hook',
    'Write two short advertisement sentences for a Saturday book fair.',
    {
      task: 'Invite families to the book fair. Name a benefit.',
      mustInclude: ['book'],
      mustNotInclude: ['or else', 'yo'],
      minWords: 10,
      maxWords: 40,
      sample: 'Find a holiday story at Saturday’s book fair. Every purchase helps our library.',
    },
    'A hook plus a benefit is enough. Threats and slang miss a school audience.',
  ),
  shortWrite(
    7,
    'advertisement',
    'audience',
    18,
    'A clear call',
    'Write one sentence that tells the reader what to do next.',
    {
      task: 'Tell families where to go on Saturday, without shouting.',
      mustInclude: ['Saturday'],
      mustNotInclude: ['or else'],
      minWords: 7,
      maxWords: 30,
      sample: 'Meet us in the hall on Saturday morning and bring a bag.',
    },
    'A call to action should be easy to follow. All-caps threats are the wrong voice.',
  ),

  // ── Unit 8 Persuasive ──
  spelling(
    8,
    'persuasive_text',
    11,
    'Find the spelling',
    'One word is spelled wrongly. Type the correct spelling.',
    'My first arguement is that Year 5 needs a longer lunch.',
    'arguement',
    ['argument'],
    'argument has no e after the u: argu-ment.',
  ),
  spelling(
    8,
    'persuasive_text',
    12,
    'A believing word',
    'Find the spelling mistake and type the word correctly.',
    'I belive a quiet reading room would help more students.',
    'belive',
    ['believe'],
    'believe keeps ie in the middle: bel-ie-ve.',
  ),
  rewrite(
    8,
    'persuasive_text',
    'audience',
    13,
    'Reason, not a rant',
    'Rewrite this rant as one respectful reason.',
    {
      original: 'This school is the worst ever and lunch is a joke!!!!',
      hint: 'State a position and a reason. Stay polite.',
      mustInclude: ['lunch'],
      mustNotInclude: ['worst', 'joke'],
      minWords: 8,
      sample: 'Year 5 should have a longer lunch because we need time to eat and still get outside.',
    },
    'Persuasive writing can be strong and still polite. Insults lose the reader.',
  ),
  rewrite(
    8,
    'persuasive_text',
    'punctuation',
    14,
    'One clear claim',
    'Rewrite this as a complete opening sentence.',
    {
      original: 'we need a quiet reading room now',
      hint: 'Capital letter and a full stop. You may add because.',
      mustInclude: ['reading'],
      minWords: 6,
      sample: 'We need a quiet reading room so more students can finish their books.',
    },
    'A claim still needs a capital and an end mark. One exclamation mark is plenty if you use one at all.',
  ),
  order(
    8,
    'persuasive_text',
    'structure',
    15,
    'Point, reason, example, close',
    'Put these persuasive sentences in a marker-friendly order.',
    [
      'Year 5 should have a longer lunch break.',
      'Many students are still eating when the bell rings.',
      'Last Tuesday I saw three classmates finish their sandwiches on the stairs.',
      'A ten-minute change would help us eat well and still play.',
    ],
    [2, 0, 3, 1],
    'Opinion, reason, a small example, then a close. That shape is easy for a marker to tick.',
  ),
  order(
    8,
    'persuasive_text',
    'format',
    16,
    'Build the case',
    'Put these quiet-reading-room lines in a clear argument order.',
    [
      'Our school should open a quiet reading room at lunch.',
      'The library floor is too noisy for students who want to finish a chapter.',
      'A Year 6 survey found 18 students looking for a quieter spot.',
      'Please try the room for one term and see the difference.',
    ],
    [1, 0, 3, 2],
    'Position, problem, evidence, request. Keep it a persuasive text, not a story or an ad.',
  ),
  shortWrite(
    8,
    'persuasive_text',
    'structure',
    17,
    'Because it matters',
    'Write two sentences: your position and one because reason.',
    {
      task: 'Argue for a longer lunch or a quiet reading room. Use because.',
      mustInclude: ['because'],
      mustNotInclude: ['worst', 'yo'],
      minWords: 12,
      maxWords: 50,
      sample: 'Year 5 should have a longer lunch. We need it because many students are still eating when the bell rings.',
    },
    'A position plus because is the core of Selective persuasive writing.',
  ),
  shortWrite(
    8,
    'persuasive_text',
    'audience',
    18,
    'A respectful close',
    'Write one closing sentence that asks without sounding rude.',
    {
      task: 'Close a persuasive paragraph to the principal. Stay polite.',
      mustInclude: ['please'],
      mustNotInclude: ['stupid', 'worst'],
      minWords: 8,
      maxWords: 35,
      sample: 'Please consider a ten-minute longer lunch for Year 5 this term.',
    },
    'A polite request keeps the audience on your side.',
  ),

  // ── Unit 9 Formal letter ──
  spelling(
    9,
    'formal_letter',
    11,
    'The sign-off',
    'Find the spelling mistake and type the word correctly.',
    'Yours sincrely, Jordan Lee',
    'sincrely',
    ['sincerely'],
    'sincerely keeps the e after the c: since-rely, but spelled sincerely.',
  ),
  spelling(
    9,
    'formal_letter',
    12,
    'A letter word',
    'Find the spelling mistake and type the word correctly.',
    'I hope you will consider this oppurtunity for Year 5.',
    'oppurtunity',
    ['opportunity'],
    'opportunity has or in the middle: oppor-tunity.',
  ),
  rewrite(
    9,
    'formal_letter',
    'format',
    13,
    'Make it a letter line',
    'Rewrite this chat message as one polite letter sentence.',
    {
      original: 'yo mr lee the bins stink ngl',
      hint: 'No slang. Name the problem clearly.',
      mustInclude: ['bins'],
      mustNotInclude: ['yo', 'ngl'],
      minWords: 8,
      sample: 'I am writing to let you know that the bins near Hall B smell strongly by lunchtime.',
    },
    'A formal letter is polite and specific. Chat slang is the wrong form.',
  ),
  rewrite(
    9,
    'formal_letter',
    'punctuation',
    14,
    'The greeting',
    'Rewrite this greeting in the usual school letter way.',
    {
      original: 'dear ms lee',
      hint: 'Capitals and a comma after the name.',
      mustInclude: ['Dear', 'Lee'],
      minWords: 3,
      requireEndPunct: false,
      sample: 'Dear Ms Lee,',
    },
    'Dear Ms Lee, is the usual school greeting. Capitals matter on titles and names.',
  ),
  order(
    9,
    'formal_letter',
    'structure',
    15,
    'Letter order',
    'Put these letter parts in the usual order.',
    [
      'Dear Ms Lee,',
      'I am writing about the bins near Hall B.',
      'By lunchtime the smell reaches the Year 5 line.',
      'Yours sincerely, Jordan Lee',
    ],
    [2, 0, 3, 1],
    'Greeting, purpose, reason, sign-off. That is the letter shape markers look for.',
  ),
  order(
    9,
    'formal_letter',
    'format',
    16,
    'Purpose then ask',
    'Put these polite lines in letter order.',
    [
      'Dear Principal Chen,',
      'I would like to request a second water tap near the oval.',
      'After sport, the one tap is not enough for two classes.',
      'Yours sincerely, Sam Ortiz',
    ],
    [1, 0, 3, 2],
    'Name the reader, state the purpose, give a reason, then sign off.',
  ),
  shortWrite(
    9,
    'formal_letter',
    'structure',
    17,
    'State the purpose',
    'Write two sentences that could open a formal letter about the bins.',
    {
      task: 'Say why you are writing and what the problem is. Stay polite.',
      mustInclude: ['bins'],
      mustNotInclude: ['yo', 'ngl'],
      minWords: 12,
      maxWords: 50,
      sample: 'I am writing about the bins near Hall B. By lunchtime the smell reaches the Year 5 line.',
    },
    'Open with the purpose. Slang and jokes do not fit a formal letter.',
  ),
  shortWrite(
    9,
    'formal_letter',
    'audience',
    18,
    'A polite request',
    'Write one sentence that asks the principal for a change.',
    {
      task: 'Ask for the bins to be emptied earlier. Use please.',
      mustInclude: ['please'],
      mustNotInclude: ['yo'],
      minWords: 8,
      maxWords: 35,
      sample: 'Please could the bins near Hall B be emptied before lunch?',
    },
    'A request with please matches a principal audience.',
  ),

  // ── Unit 10 Speech ──
  spelling(
    10,
    'speech',
    11,
    'Find the spelling',
    'One word is spelled wrongly. Type the correct spelling.',
    'We can start the quiet reading room tommorrow if we agree today.',
    'tommorrow',
    ['tomorrow'],
    'tomorrow has one m and two r’s: to-morrow.',
  ),
  spelling(
    10,
    'speech',
    12,
    'A speech word',
    'Find the spelling mistake and type the word correctly.',
    'A cleaner enviroment in the playground helps everyone.',
    'enviroment',
    ['environment'],
    'environment keeps the n after o: environ-ment.',
  ),
  rewrite(
    10,
    'speech',
    'format',
    13,
    'Say it aloud',
    'This line is a letter greeting. Rewrite it as a spoken opening.',
    {
      original: 'Dear Principal, I wish to complain about litter.',
      hint: 'Greet the listeners. Do not start with Dear.',
      mustInclude: ['everyone'],
      mustNotInclude: ['Dear', 'sincerely'],
      minWords: 6,
      sample: 'Good morning, everyone. I want to talk about litter near the oval.',
    },
    'A speech is spoken to a room. Letter greetings and sign-offs belong on paper.',
  ),
  rewrite(
    10,
    'speech',
    'audience',
    14,
    'Assembly voice',
    'Rewrite this so it could be said at assembly.',
    {
      original: 'yo this litter slaps ngl we should just leave it',
      hint: 'Clear spoken English. No chat slang.',
      mustInclude: ['litter'],
      mustNotInclude: ['yo', 'ngl', 'slaps'],
      minWords: 8,
      sample: 'The litter near the oval is a problem we can fix together.',
    },
    'Assembly listeners include teachers and younger students. Chat slang misses them.',
  ),
  order(
    10,
    'speech',
    'structure',
    15,
    'Speech order',
    'Put these spoken lines in a clear speech order.',
    [
      'Good morning, everyone.',
      'I want to talk about litter near the oval.',
      'At lunch yesterday I counted twelve wrappers on the path.',
      'Thank you for listening, and please use the bins today.',
    ],
    [2, 0, 3, 1],
    'Greet, name the point, give one example, thank the listeners.',
  ),
  order(
    10,
    'speech',
    'format',
    16,
    'Keep it spoken',
    'Put these assembly lines in an order that sounds like a speech.',
    [
      'Friends, we can make the playground cleaner this week.',
      'A clean bench means more of us want to sit outside.',
      'If each class picks up five pieces, the path will look different.',
      'Let’s start today, and thank you.',
    ],
    [1, 0, 3, 2],
    'A speech opens to the room, gives a reason, a small plan, then a close they can hear.',
  ),
  shortWrite(
    10,
    'speech',
    'structure',
    17,
    'Open the speech',
    'Write two spoken sentences that could open an assembly speech about litter.',
    {
      task: 'Greet the listeners and name your point.',
      mustInclude: ['everyone'],
      mustNotInclude: ['Dear', 'Subject'],
      minWords: 10,
      maxWords: 45,
      sample: 'Good morning, everyone. I want to talk about the litter near the oval.',
    },
    'A spoken greeting plus the point is a strong speech opening.',
  ),
  shortWrite(
    10,
    'speech',
    'audience',
    18,
    'Thank the room',
    'Write one closing sentence a speaker would say aloud.',
    {
      task: 'Thank the listeners and leave them with one thing to do.',
      mustInclude: ['thank'],
      mustNotInclude: ['sincerely'],
      minWords: 8,
      maxWords: 35,
      sample: 'Thank you for listening, and please use the bins on your way out.',
    },
    'Speeches close by thanking the room. Yours sincerely is a letter ending.',
  ),

  // ── Unit 11 Email ──
  spelling(
    11,
    'email',
    11,
    'Find the spelling',
    'One word is spelled wrongly. Type the correct spelling.',
    'Please send the excursion note to my home adress.',
    'adress',
    ['address'],
    'address has two d’s: ad-dress.',
  ),
  spelling(
    11,
    'email',
    12,
    'A school word',
    'Find the spelling mistake and type the word correctly.',
    'Thank you for writting back so quickly.',
    'writting',
    ['writing'],
    'writing has one t: writ-ing (from write, drop the e).',
  ),
  rewrite(
    11,
    'email',
    'format',
    13,
    'Make it an email',
    'Rewrite this shout as one polite email sentence.',
    {
      original: 'CAN I GET THE LINK!!!!',
      hint: 'Ask clearly. No all caps.',
      mustInclude: ['link'],
      mustNotInclude: ['yo'],
      minWords: 7,
      sample: 'Could you please send the homework link when you have a moment?',
    },
    'A teacher email is short and polite. All-caps shouting is the wrong form.',
  ),
  rewrite(
    11,
    'email',
    'punctuation',
    14,
    'Greeting comma',
    'Rewrite this email greeting in the usual way.',
    {
      original: 'dear ms lee',
      hint: 'Capitals and a comma after the name.',
      mustInclude: ['Dear', 'Lee'],
      minWords: 3,
      requireEndPunct: false,
      sample: 'Dear Ms Lee,',
    },
    'Dear Ms Lee, is the usual school email greeting.',
  ),
  order(
    11,
    'email',
    'structure',
    15,
    'Email order',
    'Put these email lines in a clear order.',
    [
      'Dear Ms Lee,',
      'I am writing to ask for the homework link from Tuesday.',
      'I was away at the dentist and missed the last five minutes.',
      'Thank you for your time.',
    ],
    [2, 0, 3, 1],
    'Greeting, purpose, a short reason, thanks. One job per email.',
  ),
  order(
    11,
    'email',
    'format',
    16,
    'Keep one job',
    'Put these polite lines in email order.',
    [
      'Dear Coach Nguyen,',
      'Could I please change to Thursday training this week?',
      'I have a dentist appointment on Wednesday afternoon.',
      'Kind regards, Sam Ortiz',
    ],
    [1, 0, 3, 2],
    'Name the reader, ask for one thing, give the reason, then close.',
  ),
  shortWrite(
    11,
    'email',
    'structure',
    17,
    'One clear ask',
    'Write two sentences that could be the body of a teacher email.',
    {
      task: 'Ask for a homework link. Give one short reason.',
      mustInclude: ['link'],
      mustNotInclude: ['yo', 'lol'],
      minWords: 12,
      maxWords: 50,
      sample: 'Could you please send the homework link from Tuesday? I was away at the dentist and missed the last five minutes.',
    },
    'One ask plus a reason is enough. Slang and long stories make the email harder to answer.',
  ),
  shortWrite(
    11,
    'email',
    'audience',
    18,
    'A polite close',
    'Write one closing sentence for a teacher email.',
    {
      task: 'Thank the teacher. Keep it short.',
      mustInclude: ['thank'],
      mustNotInclude: ['yo', 'thx'],
      minWords: 5,
      maxWords: 20,
      sample: 'Thank you for your time.',
    },
    'Thank you for your time is simple and polite. Chat shortenings are too casual.',
  ),
];
