#!/usr/bin/env bash
# Idempotent Cloud Agent install for oc-selective.
# Prepares a self-contained local PostgreSQL, installs Node dependencies,
# applies the SQL schema, and seeds writing prompts.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

DB_NAME="oc_selective"
DB_USER="ocuser"
DB_PASSWORD="ocpassword"
DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/${DB_NAME}"

echo "[install] Ensuring PostgreSQL is installed..."
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi

# Detect the installed PostgreSQL major version / cluster.
PG_VERSION="$(pg_lsclusters -h | awk 'NR==1 {print $1}')"
PG_CLUSTER="$(pg_lsclusters -h | awk 'NR==1 {print $2}')"
: "${PG_VERSION:=16}"
: "${PG_CLUSTER:=main}"

echo "[install] Starting PostgreSQL cluster ${PG_VERSION}/${PG_CLUSTER}..."
if ! pg_lsclusters -h | awk '{print $4}' | grep -q online; then
  sudo pg_ctlcluster "$PG_VERSION" "$PG_CLUSTER" start
fi

echo "[install] Waiting for PostgreSQL to accept connections..."
for _ in $(seq 1 30); do
  if pg_isready -h 127.0.0.1 -p 5432 >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

echo "[install] Ensuring database role and database exist..."
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}';
  END IF;
END\$\$;
SQL
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1; then
  sudo -u postgres createdb -O "$DB_USER" "$DB_NAME"
fi
sudo -u postgres psql -v ON_ERROR_STOP=1 -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};"

echo "[install] Writing .env.local if missing..."
if [ ! -f .env.local ]; then
  cat > .env.local <<ENV
# Local development environment (Cloud Agent) — generated by .cursor/install.sh
DATABASE_URL=${DATABASE_URL}
JWT_SECRET=local-dev-jwt-secret-change-me-in-production
# OpenAI scoring is optional: without a key the app uses heuristic fallback scoring.
# OPENAI_API_KEY=sk-...
OPENAI_MODEL=gpt-4o-mini
ENV
fi

echo "[install] Installing Node dependencies..."
if [ -f package-lock.json ]; then
  npm ci
else
  npm install
fi

echo "[install] Applying SQL schema (idempotent)..."
PGPASSWORD="$DB_PASSWORD" psql -v ON_ERROR_STOP=1 "$DATABASE_URL" -f sql/schema.sql
PGPASSWORD="$DB_PASSWORD" psql -v ON_ERROR_STOP=1 "$DATABASE_URL" -f sql/writing_schema.sql

echo "[install] Seeding writing prompts (skips if already seeded)..."
npm run db:seed-writing

echo "[install] Done."
